GravityBall: C:/Users/Kat/Documents/PROJECTS/ICT290/2015shayLearyALL/CAMPUS_TOUR/EasySound.h File Reference
C:/Users/Kat/Documents/PROJECTS/ICT290/2015shayLearyALL/CAMPUS_TOUR/EasySound.h File Reference
#include <stdlib.h>
#include <SDL.h>
#include <list>
#include "Sound.h"
#include "SoundTime.h"
Classes
class CEasySound
Defines
#define ES_SAMPLE 8192
#define ES_FREQ 88200
Functions
void mixaudio (void *unused, Uint8 *stream, int len)
Define Documentation
#define ES_FREQ 88200
Definition at line 28 of file EasySound.h.
Referenced by CEasySound::CEasySound().
#define ES_SAMPLE 8192
class Score: This class displays the score, bonus and time on the screen
Author:
Shay Leary
Definition at line 27 of file EasySound.h.
Referenced by CEasySound::CEasySound().
Function Documentation
void mixaudio (void * unused, Uint8 * stream, int len)
Definition at line 6 of file EasySound.cpp.
References CEasySound::CallMixAudio(), and CEasySound::Instance().
Referenced by CEasySound::CEasySound().
{
        CEasySound::Instance()->CallMixAudio(unused,stream,len);
}