GravityBall: C:/Users/Kat/Documents/PROJECTS/ICT290/2015shayLearyALL/CAMPUS_TOUR/EasySound.cpp File Reference
C:/Users/Kat/Documents/PROJECTS/ICT290/2015shayLearyALL/CAMPUS_TOUR/EasySound.cpp File Reference
#include "EasySound.h"
Functions
void mixaudio (void *unused, Uint8 *stream, int len)
Function Documentation
void mixaudio (void * unused, Uint8 * stream, int len)
Definition at line 6 of file EasySound.cpp.
References CEasySound::CallMixAudio(), and CEasySound::Instance().
Referenced by CEasySound::CEasySound().
{
        CEasySound::Instance()->CallMixAudio(unused,stream,len);
}