GravityBall: CEasySound Class Reference
CEasySound Class Reference
#include <EasySound.h>
Public Member Functions
virtual ~CEasySound ()
void CallMixAudio (void *unused, Uint8 *stream, int len)
int Load (char *filename)
void Unload (int iSoundID)
void Unload (CSound *sound)
CSound * GetSound (int iSoundID)
SDL_AudioSpec GetObtained ()
Static Public Member Functions
static CEasySound * Instance ()
Protected Member Functions
CEasySound ()
Private Attributes
std::list< CSound * > m_listSound
SDL_AudioSpec desired
SDL_AudioSpec obtained
Static Private Attributes
static CEasySound * _instance = NULL
Detailed Description
class CEasySound: This class is singleton design pattern, and it control all object related to sound. (use SDL library)
Author:
Shannon, Graham and Shay
Definition at line 36 of file EasySound.h.
Constructor & Destructor Documentation
CEasySound::~CEasySound () [virtual]
~CEasySound:
Returns:
Definition at line 55 of file EasySound.cpp.
References _instance.
{
        SDL_Quit();
        delete _instance;
        _instance = NULL;
}
CEasySound::CEasySound () [protected]
CEasySound: The construction had to be protected because of Singleton Design Pattern
Returns:
Definition at line 20 of file EasySound.cpp.
References desired, ES_FREQ, ES_SAMPLE, mixaudio(), and obtained.
Referenced by Instance().
{
  if ((SDL_Init(SDL_INIT_VIDEO|SDL_INIT_AUDIO|SDL_INIT_NOPARACHUTE)==-1))  {
      fprintf(stderr, "Unable to init SDL: %s\n", SDL_GetError());
      exit(1);
  }
  atexit(SDL_Quit);
        /* Open the audio device */
        /* 22050Hz - FM Radio quality */
        desired.freq=ES_FREQ;
        /* 16-bit signed audio */
        desired.format=AUDIO_S16;
        /* Mono */
        desired.channels=2;
        /* Large audio buffer reduces risk of dropouts but increases response time */
        desired.samples=ES_SAMPLE;
        desired.callback = mixaudio;
        desired.userdata=NULL;
        /* Open the audio device */
        if ( SDL_OpenAudio(&desired, &obtained) < 0 ){
                fprintf(stderr, "Couldn't open audio: %s\n", SDL_GetError());
                exit(-1);
        }
}
Member Function Documentation
CEasySound * CEasySound::Instance () [static]
Instance: Get CEasySound class before using any methods (Singleton Design Pattern)
Returns:
static CEasySound*
Definition at line 62 of file EasySound.cpp.
References _instance, and CEasySound().
Referenced by Camera::Camera(), CSound::CSound(), mixaudio(), uiHUD::mouseUIHUD(), uiLeaderBoard::mouseUILeaderBoard(), uiMenu::mouseUIMenu(), uiOptions::mouseUIOptions(), uiScore::mouseUIScore(), and myinit().
{
        if (_instance == NULL)
                _instance = new CEasySound();
        return _instance;
}
void CEasySound::CallMixAudio (void * unused, Uint8 * stream, int len)
CallMixAudio: ? no idea eh
Parameters:
unused
stream
len
Returns:
void
Definition at line 69 of file EasySound.cpp.
References m_listSound.
Referenced by mixaudio().
{
        SDL_memset(stream, 0, len); // KM 2/9/2016 new with SDL2, stops sound repeating
        //int i;
    Uint32 amount, data_len, data_pos;
        std::list<CSound*>::iterator cs;
        for (cs = m_listSound.begin(); cs != m_listSound.end(); ++cs) {
                //data_len = (*cs)->GetLength().GetSDLTime();
                data_len = (*cs)->m_stop.GetSDLTime();
                data_pos = (*cs)->m_pos.GetSDLTime();
                amount = (data_len - data_pos);
                if ( amount > len) {
                        amount = len;
                }
                Uint8 *data = &(*cs)->m_data[data_pos];
                SDL_MixAudio(stream, data, amount, SDL_MIX_MAXVOLUME);
                (*cs)->m_pos = CSoundTime(data_pos + amount);
        }
}
int CEasySound::Load (char * filename)
Load: load the sound and store in the m_listSound list
Parameters:
filename - filename of sound wave file
Returns:
int - get sound's ID for future use
Definition at line 93 of file EasySound.cpp.
References CSound::GetLength(), and m_listSound.
Referenced by Camera::Camera(), uiHUD::mouseUIHUD(), uiLeaderBoard::mouseUILeaderBoard(), uiMenu::mouseUIMenu(), uiOptions::mouseUIOptions(), uiScore::mouseUIScore(), and myinit().
{
        // find ID for sound
        std::list<CSound*>::iterator cs;
        int iSoundID = 0;
        bool bFoundID = true;
        while( bFoundID ) { // while loop until if there no ID match and set that ID for new sound's ID
                bFoundID = false;
                for (cs = m_listSound.begin(); cs != m_listSound.end(); ++cs) {
                        if ((*cs)->GetSoundID() == iSoundID) {
                                bFoundID = true;
                                iSoundID++;
                                break;
                        }
                }
        }
        // load the sound with new ID
        CSound* sound = new CSound(filename,iSoundID);
        if (sound->GetLength() == CSoundTime(0,0,0)) {
                return -1; // fail to load
        }
        m_listSound.insert(m_listSound.end(),sound);
        return iSoundID; // fail to load
}
void CEasySound::Unload (int iSoundID)
Unload: unload the sound and remove form the m_listSound list
Parameters:
iSoundID - Sound's ID to find if there match ID in the m_listSound and unload it.
Returns:
void
Definition at line 119 of file EasySound.cpp.
References m_listSound.
Referenced by Camera::~Camera().
{
        std::list<CSound*>::iterator cs;
        for (cs = m_listSound.begin(); cs != m_listSound.end(); ++cs) {
                if ((*cs)->GetSoundID() == iSoundID) {
                        m_listSound.erase(cs);
                        delete (*cs);
                        return;
                }
        }
}
void CEasySound::Unload (CSound * sound)
Unload: unload the sound and remove from the m_listSound list
Parameters:
sound - CSound class to find if there match ID in the m_listSound and unload it.
Returns:
void
Definition at line 131 of file EasySound.cpp.
References CSound::GetSoundID(), and m_listSound.
{
        std::list<CSound*>::iterator cs;
        for (cs = m_listSound.begin(); cs != m_listSound.end(); ++cs) {
                if ((*cs)->GetSoundID() == sound->GetSoundID()) {
                        m_listSound.erase(cs);
                        //delete (*cs);  //KM 2/9/2016 Debug Assertion that iterator not dereferencable, maybe from here? assertion doesn't happen when this commented out but sound is still messed up.
                        return;
                }
        }
}
CSound * CEasySound::GetSound (int iSoundID)
GetSound: get the sound from the m_listSound list
Parameters:
iSoundID - Sound's ID to be given before get Sound Object from the m_listSound
Returns:
CSound* - Sound Object to use it (Play, Stop, etc)
Definition at line 143 of file EasySound.cpp.
References m_listSound.
Referenced by Camera::Camera(), uiHUD::mouseUIHUD(), uiLeaderBoard::mouseUILeaderBoard(), uiMenu::mouseUIMenu(), uiOptions::mouseUIOptions(), uiScore::mouseUIScore(), and myinit().
{
        std::list<CSound*>::iterator cs;
        for (cs = m_listSound.begin(); cs != m_listSound.end(); ++cs) {
                if ((*cs)->GetSoundID() == iSoundID) {
                        return (*cs);
                }
        }
        return NULL; // empty sound
}
SDL_AudioSpec CEasySound::GetObtained () [inline]
Definition at line 91 of file EasySound.h.
References obtained.
Referenced by CSound::CSound().
{ return obtained; };
Member Data Documentation
CEasySound * CEasySound::_instance = NULL [static, private]
_instance: pointer of CEasySound class as part of the Singleton Design Pattern
Definition at line 104 of file EasySound.h.
Referenced by Instance(), and ~CEasySound().
std::list<CSound*> CEasySound::m_listSound [private]
m_listSound: list of Sound's object to store it. (STL's list object)
Definition at line 109 of file EasySound.h.
Referenced by CallMixAudio(), GetSound(), Load(), and Unload().
SDL_AudioSpec CEasySound::desired [private]
Definition at line 111 of file EasySound.h.
Referenced by CEasySound().
SDL_AudioSpec CEasySound::obtained [private]
Definition at line 112 of file EasySound.h.
Referenced by CEasySound(), and GetObtained().
The documentation for this class was generated from the following files:
C:/Users/Kat/Documents/PROJECTS/ICT290/2015shayLearyALL/CAMPUS_TOUR/EasySound.h
C:/Users/Kat/Documents/PROJECTS/ICT290/2015shayLearyALL/CAMPUS_TOUR/EasySound.cpp