GravityBall: Camera Class Reference
Camera Class Reference
#include <camera.h>
Public Member Functions
Camera ()
virtual ~Camera ()
void SetAABBMaxX (const int &tempIndex, const GLdouble &tempX)
void SetAABBMinX (const int &tempIndex, const GLdouble &tempX)
void SetAABBMaxY (const int &tempIndex, const GLdouble &tempY)
void SetAABBMinY (const int &tempIndex, const GLdouble &tempY)
void SetAABBMaxZ (const int &tempIndex, const GLdouble &tempZ)
void SetAABBMinZ (const int &tempIndex, const GLdouble &tempZ)
void SetRotateSpeed (const GLdouble &tempSpeed)
void SetMoveSpeed (const GLdouble &tempSpeed)
void SetCollisionDetectionOn (const bool &tempCol)
void SetNoBoundingBoxes (const int &tempSize)
void SetWorldCoordinates (const GLdouble &tempX, const GLdouble &tempZ)
void InitiateBoundingBoxes ()
void SetPlains (const int tempType, const GLdouble tempXs, const GLdouble tempXe, const GLdouble tempYs, const GLdouble tempYe, const GLdouble tempZs, const GLdouble tempZe)
GLdouble GetLR ()
GLdouble GetUD ()
GLdouble GetFB ()
GLdouble GetAABBMaxX (const int &tempIndex)
GLdouble GetAABBMinX (const int &tempIndex)
GLdouble GetAABBMaxY (const int &tempIndex)
GLdouble GetAABBMinY (const int &tempIndex)
GLdouble GetAABBMaxZ (const int &tempIndex)
GLdouble GetAABBMinZ (const int &tempIndex)
void Position (GLdouble const &tempX, GLdouble const &tempY, GLdouble const &tempZ, GLdouble const &tempAngle)
void CheckCamera ()
void DirectionFB (int const &tempMove)
void DirectionLR (int const &tempMove)
void DirectionUD (int const &tempMove)
void DirectionRotateLR (GLdouble const &tempMove)
void DirectionLookUD (int const &tempMove)
void DisplayMap (const int &screenWidth, const int &screenHeight, const GLuint &tempImage)
void DisplayWelcomeScreen (const int &screenWidth, const int &screenHeight, const int &tempExit, const GLuint &tempImage)
void DisplayNoExit (const int &screenWidth, const int &screenHeight, const GLuint &tempImage)
Private Member Functions
bool MoveFBOK ()
bool MoveLROK ()
bool MoveUDOK ()
bool RotateLROK ()
bool LookUDOK ()
void MoveFB ()
void MoveLR ()
void MoveUD ()
void RotateLR ()
void LookUD ()
void SetPlains (const int &moveX, const int &moveZ)
void ResetXYZ ()
void callGLLookAt ()
void ClimbSteps (GLdouble stepStart, GLdouble stepFinish, GLdouble stepHeight, GLdouble stepWidth, int noSteps)
void CheckSteps ()
Camera (const Camera &cam)
Camera & operator= (const Camera &cam)
Private Attributes
GLdouble m_incrementX
GLdouble m_incrementZ
int m_No_Plains
int m_plainNo
GLdouble m_plainHeight
GLdouble m_rotateAngleLR
GLdouble m_deltaAngleLR
GLdouble m_rotateAngleUD
GLdouble m_deltaAngleUD
GLdouble m_x
GLdouble m_y
GLdouble m_z
GLdouble m_zLast
GLdouble m_xLast
GLdouble m_lookX
GLdouble m_lookY
GLdouble m_lookZ
GLdouble m_lookXX
GLdouble m_lookYY
GLdouble m_lookZZ
GLdouble m_deltaMoveLR
GLdouble m_deltaMoveFB
GLdouble m_deltaMoveUD
GLdouble m_direction
GLdouble m_rotateSpeed
GLdouble m_moveSpeed
bool m_CollisionDetectionOn
Collision m_colDetect
CameraMap m_map
PlainLinkedList m_Plain
CEasySound * es
CSound * stepSound
Detailed Description
Definition at line 20 of file camera.h.
Constructor & Destructor Documentation
Camera::Camera ()
Definition at line 18 of file camera.cpp.
References es, CEasySound::GetSound(), CEasySound::Instance(), CEasySound::Load(), m_CollisionDetectionOn, m_deltaAngleLR, m_deltaAngleUD, m_deltaMoveFB, m_deltaMoveLR, m_deltaMoveUD, m_moveSpeed, m_rotateAngleLR, m_rotateAngleUD, m_rotateSpeed, ResetXYZ(), and stepSound.
{
        m_rotateSpeed = 0.0f;
        m_moveSpeed = 0.0f;
        ResetXYZ();
        m_deltaMoveFB = 0;
        m_deltaMoveLR = 0;
        m_deltaMoveUD = 0;
        m_rotateAngleLR = 0.0;
        m_rotateAngleUD = 0.0;
        m_deltaAngleLR = 0.0;
        m_deltaAngleUD = 0.0;
        m_CollisionDetectionOn = true;
        // sound objects
        es = CEasySound::Instance();
        stepSound = es->GetSound(es->Load("sounds/step.wav"));
}
virtual Camera::~Camera () [inline, virtual]
Definition at line 25 of file camera.h.
References es, stepSound, and CEasySound::Unload().
{es->Unload(stepSound);}
Camera::Camera (const Camera & cam) [inline, private]
Definition at line 168 of file camera.h.
{};
Member Function Documentation
void Camera::SetAABBMaxX (const int & tempIndex, const GLdouble & tempX) [inline]
Definition at line 33 of file camera.h.
References m_colDetect, and Collision::SetAABBMaxX().
Referenced by CreateBoundingBoxes().
{m_colDetect.SetAABBMaxX(tempIndex, tempX);}
void Camera::SetAABBMinX (const int & tempIndex, const GLdouble & tempX) [inline]
Definition at line 34 of file camera.h.
References m_colDetect, and Collision::SetAABBMinX().
Referenced by CreateBoundingBoxes().
{m_colDetect.SetAABBMinX(tempIndex, tempX);}
void Camera::SetAABBMaxY (const int & tempIndex, const GLdouble & tempY) [inline]
Definition at line 35 of file camera.h.
References m_colDetect, and Collision::SetAABBMaxY().
{m_colDetect.SetAABBMaxY(tempIndex, tempY);}
void Camera::SetAABBMinY (const int & tempIndex, const GLdouble & tempY) [inline]
Definition at line 36 of file camera.h.
References m_colDetect, and Collision::SetAABBMinY().
{m_colDetect.SetAABBMinY(tempIndex, tempY);}
void Camera::SetAABBMaxZ (const int & tempIndex, const GLdouble & tempZ) [inline]
Definition at line 37 of file camera.h.
References m_colDetect, and Collision::SetAABBMaxZ().
Referenced by CreateBoundingBoxes().
{m_colDetect.SetAABBMaxZ(tempIndex, tempZ);}
void Camera::SetAABBMinZ (const int & tempIndex, const GLdouble & tempZ) [inline]
Definition at line 38 of file camera.h.
References m_colDetect, and Collision::SetAABBMinZ().
Referenced by CreateBoundingBoxes().
{m_colDetect.SetAABBMinZ(tempIndex, tempZ);}
void Camera::SetRotateSpeed (const GLdouble & tempSpeed) [inline]
Definition at line 41 of file camera.h.
References m_rotateSpeed.
Referenced by Display(), and keys().
{m_rotateSpeed = tempSpeed;}
void Camera::SetMoveSpeed (const GLdouble & tempSpeed) [inline]
Definition at line 42 of file camera.h.
References m_moveSpeed.
Referenced by Display(), and keys().
{m_moveSpeed = tempSpeed;}
void Camera::SetCollisionDetectionOn (const bool & tempCol) [inline]
Definition at line 46 of file camera.h.
References m_CollisionDetectionOn.
Referenced by myinit().
{m_CollisionDetectionOn = tempCol;}
void Camera::SetNoBoundingBoxes (const int & tempSize) [inline]
Definition at line 48 of file camera.h.
References m_colDetect, and Collision::SetNoBoundingBoxes().
Referenced by myinit().
{m_colDetect.SetNoBoundingBoxes(tempSize);}
void Camera::SetWorldCoordinates (const GLdouble & tempX, const GLdouble & tempZ)
Definition at line 445 of file camera.cpp.
References m_colDetect, Collision::SetWorldX(), and Collision::SetWorldZ().
Referenced by myinit().
{
        m_colDetect.SetWorldX(tempX);
        m_colDetect.SetWorldZ(tempZ);
}
void Camera::InitiateBoundingBoxes () [inline]
Definition at line 53 of file camera.h.
References Collision::CreateLinkedList(), and m_colDetect.
Referenced by myinit().
{m_colDetect.CreateLinkedList();}
void Camera::SetPlains (const int tempType, const GLdouble tempXs, const GLdouble tempXe, const GLdouble tempYs, const GLdouble tempYe, const GLdouble tempZs, const GLdouble tempZe)
Definition at line 453 of file camera.cpp.
References PlainLinkedList::AddToStart(), and m_Plain.
Referenced by CreatePlains(), MoveFB(), and MoveLR().
{
        m_Plain.AddToStart(tempType, tempXs, tempXe, tempYs, tempYe, tempZs, tempZe);
}
GLdouble Camera::GetLR () [inline]
Definition at line 64 of file camera.h.
References m_x.
Referenced by addParticle(), CheckLocationForTeleport(), Display(), DisplayMap(), keys(), OpenSlidingDoor(), and UpdateCamCollider().
{return m_x;}
GLdouble Camera::GetUD () [inline]
Definition at line 65 of file camera.h.
References m_y.
Referenced by addParticle(), CheckLocationForTeleport(), Display(), keys(), OpenSlidingDoor(), and UpdateCamCollider().
{return m_y;}
GLdouble Camera::GetFB () [inline]
Definition at line 66 of file camera.h.
References m_z.
Referenced by addParticle(), CheckLocationForTeleport(), Display(), DisplayMap(), keys(), OpenSlidingDoor(), TeleportToPlanets(), and UpdateCamCollider().
{return m_z;}
GLdouble Camera::GetAABBMaxX (const int & tempIndex) [inline]
Definition at line 67 of file camera.h.
References Collision::GetAABBMaxX(), and m_colDetect.
{return m_colDetect.GetAABBMaxX (tempIndex);}
GLdouble Camera::GetAABBMinX (const int & tempIndex) [inline]
Definition at line 68 of file camera.h.
References Collision::GetAABBMinX(), and m_colDetect.
{return m_colDetect.GetAABBMinX (tempIndex);}
GLdouble Camera::GetAABBMaxY (const int & tempIndex) [inline]
Definition at line 69 of file camera.h.
References Collision::GetAABBMaxY(), and m_colDetect.
{return m_colDetect.GetAABBMaxY (tempIndex);}
GLdouble Camera::GetAABBMinY (const int & tempIndex) [inline]
Definition at line 70 of file camera.h.
References Collision::GetAABBMinY(), and m_colDetect.
{return m_colDetect.GetAABBMinY (tempIndex);}
GLdouble Camera::GetAABBMaxZ (const int & tempIndex) [inline]
Definition at line 71 of file camera.h.
References Collision::GetAABBMaxZ(), and m_colDetect.
{return m_colDetect.GetAABBMaxZ (tempIndex);}
GLdouble Camera::GetAABBMinZ (const int & tempIndex) [inline]
Definition at line 72 of file camera.h.
References Collision::GetAABBMinZ(), and m_colDetect.
{return m_colDetect.GetAABBMinZ (tempIndex);}
void Camera::Position (GLdouble const & tempX, GLdouble const & tempY, GLdouble const & tempZ, GLdouble const & tempAngle)
Definition at line 367 of file camera.cpp.
References callGLLookAt(), m_deltaAngleUD, m_lookX, m_lookXX, m_lookZ, m_lookZZ, m_rotateAngleLR, m_rotateAngleUD, m_x, m_y, m_z, PI, and ResetXYZ().
Referenced by myinit(), TeleportToBushCourt(), and TeleportToPlanets().
{
        ResetXYZ();
        m_x = tempX;
        m_y = tempY;
        m_z = tempZ;
        // rotate to correct angle
        m_rotateAngleLR = tempAngle * (PI / 180);
        m_lookX = sin(m_rotateAngleLR);
        m_lookZ = -cos(m_rotateAngleLR);
        m_lookXX = sin(m_rotateAngleLR + (float) PI/2.0);
        m_lookZZ = -cos(m_rotateAngleLR + (float) PI/2.0);
        m_rotateAngleUD = 0.0;
        m_deltaAngleUD = 0.0;
        // redislay
        callGLLookAt();
}
void Camera::CheckCamera ()
Definition at line 392 of file camera.cpp.
References LookUD(), LookUDOK(), MoveFB(), MoveFBOK(), MoveLR(), MoveLROK(), MoveUD(), MoveUDOK(), RotateLR(), and RotateLROK().
Referenced by Display().
{
        if (MoveFBOK()) MoveFB();
        if (MoveLROK()) MoveLR();
        if (MoveUDOK()) MoveUD();
        if (RotateLROK()) RotateLR();
        if (LookUDOK()) LookUD();
}
void Camera::DirectionFB (int const & tempMove)
Definition at line 62 of file camera.cpp.
References m_deltaMoveFB.
Referenced by ClimbSteps(), keys(), and releaseKeys().
{
        m_deltaMoveFB = tempMove;
}
void Camera::DirectionLR (int const & tempMove)
Definition at line 67 of file camera.cpp.
References m_deltaMoveLR.
Referenced by ClimbSteps(), keys(), and releaseKeys().
{
        m_deltaMoveLR = tempMove;
}
void Camera::DirectionUD (int const & tempMove)
Definition at line 73 of file camera.cpp.
References m_deltaMoveUD.
{
        m_deltaMoveUD = tempMove;
}
void Camera::DirectionRotateLR (GLdouble const & tempMove)
Definition at line 79 of file camera.cpp.
References m_deltaAngleLR, and m_rotateSpeed.
Referenced by keys(), mouseMove(), and releaseKeys().
{
        m_deltaAngleLR = tempMove * m_rotateSpeed;
}
void Camera::DirectionLookUD (int const & tempMove)
Definition at line 85 of file camera.cpp.
References m_deltaAngleUD, and m_rotateSpeed.
Referenced by keys(), mouseMove(), and releaseKeys().
{
        m_deltaAngleUD = tempMove * m_rotateSpeed;
}
void Camera::DisplayMap (const int & screenWidth, const int & screenHeight, const GLuint & tempImage)
Definition at line 417 of file camera.cpp.
References CameraMap::DisplayMap(), GetFB(), GetLR(), and m_map.
Referenced by Display().
{
        m_map.DisplayMap(screenWidth, screenHeight, GetLR (), GetFB (), tempImage);
}
void Camera::DisplayWelcomeScreen (const int & screenWidth, const int & screenHeight, const int & tempExit, const GLuint & tempImage)
Definition at line 427 of file camera.cpp.
References CameraMap::DisplayWelcomeScreen(), and m_map.
Referenced by Display().
{
         m_map.DisplayWelcomeScreen(screenWidth, screenHeight, tempExit, tempImage);
}
void Camera::DisplayNoExit (const int & screenWidth, const int & screenHeight, const GLuint & tempImage)
Definition at line 437 of file camera.cpp.
References CameraMap::DisplayNoExit(), and m_map.
{
         m_map.DisplayNoExit(screenWidth, screenHeight, tempImage);
}
bool Camera::MoveFBOK () [private]
Definition at line 94 of file camera.cpp.
Referenced by CheckCamera().
{
        bool tempReturn;
        if (m_deltaMoveFB < 0 || m_deltaMoveFB > 0)
        {
                tempReturn = true;
        }
        else
        {
                tempReturn = false;
        }
        return tempReturn;
}
bool Camera::MoveLROK () [private]
Definition at line 111 of file camera.cpp.
Referenced by CheckCamera().
{
        bool tempReturn;
        if (m_deltaMoveLR < 0 || m_deltaMoveLR > 0)
        {
                tempReturn = true;
        }
        else
        {
                tempReturn = false;
        }
        return tempReturn;
}
bool Camera::MoveUDOK () [private]
Definition at line 128 of file camera.cpp.
Referenced by CheckCamera().
{
        bool tempReturn;
        if (m_deltaMoveUD < 0 || m_deltaMoveUD > 0)
        {
                tempReturn = true;
        }
        else
        {
                tempReturn = false;
        }
        return tempReturn;
}
bool Camera::RotateLROK () [private]
Definition at line 145 of file camera.cpp.
References m_deltaAngleLR, and m_rotateSpeed.
Referenced by CheckCamera().
{
        bool tempReturn;
        if ((m_deltaAngleLR/m_rotateSpeed) < 0 || (m_deltaAngleLR/m_rotateSpeed) > 0)
        {
                tempReturn = true;
        }
        else
        {
                tempReturn = false;
        }
        return tempReturn;
}
bool Camera::LookUDOK () [private]
Definition at line 162 of file camera.cpp.
References m_deltaAngleUD, and m_rotateSpeed.
Referenced by CheckCamera().
{
        bool tempReturn;
        if ((m_deltaAngleUD/m_rotateSpeed) < 0 || (m_deltaAngleUD/m_rotateSpeed) > 0)
        {
                tempReturn = true;
        }
        else
        {
                tempReturn = false;
        }
        return tempReturn;
}
void Camera::MoveFB () [private]
Definition at line 179 of file camera.cpp.
References callGLLookAt(), Collision::Collide(), m_colDetect, m_CollisionDetectionOn, m_deltaMoveFB, m_lookX, m_lookY, m_lookZ, m_moveSpeed, m_x, m_xLast, m_y, m_z, m_zLast, and SetPlains().
Referenced by CheckCamera().
{
        // record previous co-ordinates
        m_xLast = m_x;
        m_zLast = m_z;
        // set movement step
        GLdouble moveZ = (m_deltaMoveFB * (m_lookZ) * m_moveSpeed);
        GLdouble moveX = (m_deltaMoveFB * (m_lookX) * m_moveSpeed);
        if (m_CollisionDetectionOn)
        {
                GLdouble startX = m_x + moveX * 5.0;
                GLdouble startZ = m_z + moveZ * 5.0;
                // check if collsion
                if (!(m_colDetect.Collide(startX + m_lookX, m_y + m_lookY, startZ + m_lookZ)))
                {
                        // increment position
                        m_x += moveX;
                        m_z += moveZ;
                        // check plain
                        SetPlains(moveX, moveZ);
                        // redisplay
                        callGLLookAt();
                }
        }
        else
        {
                // increment position
                m_x += moveX;
                m_z += moveZ;
                // check plain
                SetPlains(moveX, moveZ);
                // redisplay
                callGLLookAt();
        }
}
void Camera::MoveLR () [private]
Definition at line 221 of file camera.cpp.
References callGLLookAt(), Collision::Collide(), m_colDetect, m_CollisionDetectionOn, m_deltaMoveLR, m_lookXX, m_lookYY, m_lookZZ, m_moveSpeed, m_x, m_xLast, m_y, m_z, m_zLast, and SetPlains().
Referenced by CheckCamera().
{
        // record previous co-ordinates
        m_zLast = m_z;
        m_xLast = m_x;
        // set movement step
        GLdouble moveZ = (m_deltaMoveLR * (m_lookZZ) * m_moveSpeed);
        GLdouble moveX = (m_deltaMoveLR * (m_lookXX) * m_moveSpeed);
        if (m_CollisionDetectionOn)
        {
                GLdouble startX = m_x + moveX * 1.0;
                GLdouble startZ = m_z + moveZ * m_moveSpeed * 1.0;
                // check if collsion
                if (!(m_colDetect.Collide(startX + m_lookXX, m_y + m_lookYY, startZ + m_lookZZ)))
                {
                        // increment position
                        m_x += moveX;
                        m_z += moveZ;
                        // check plain
                        SetPlains(moveX, moveZ);
                        // redisplay
                        callGLLookAt();
                }
        }
        else
        {
                // increment position
                m_x += moveX;
                m_z += moveZ;
                SetPlains(moveX, moveZ);
                // redisplay
                callGLLookAt();
        }
}
void Camera::MoveUD () [private]
Definition at line 322 of file camera.cpp.
References callGLLookAt(), Collision::Collide(), m_colDetect, m_CollisionDetectionOn, m_deltaMoveUD, m_lookXX, m_lookYY, m_lookZZ, m_moveSpeed, m_x, m_y, and m_z.
Referenced by CheckCamera().
{
        if (m_CollisionDetectionOn)
        {
                GLdouble startY = m_y + m_deltaMoveUD * (m_lookYY) * m_moveSpeed * 5.0;
                if (!(m_colDetect.Collide(m_x + m_lookXX, startY + m_lookYY, m_z + m_lookZZ)))
                {
                        m_y += m_deltaMoveUD * (m_lookYY) * m_moveSpeed;
                        callGLLookAt();
                }
        }
        else
        {
                m_y += m_deltaMoveUD * (m_lookYY) * m_moveSpeed;
                callGLLookAt();
        }
}
void Camera::RotateLR () [private]
Definition at line 344 of file camera.cpp.
References callGLLookAt(), m_deltaAngleLR, m_lookX, m_lookXX, m_lookZ, m_lookZZ, m_rotateAngleLR, and PI.
Referenced by CheckCamera().
{
        m_rotateAngleLR += m_deltaAngleLR;
        m_lookX = sin(m_rotateAngleLR);
        m_lookZ = -cos(m_rotateAngleLR);
        m_lookXX = sin(m_rotateAngleLR + (float) PI/2.0);
        m_lookZZ = -cos(m_rotateAngleLR + (float) PI/2.0);
        callGLLookAt();
}
void Camera::LookUD () [private]
Definition at line 357 of file camera.cpp.
References callGLLookAt(), m_deltaAngleUD, m_lookY, and m_rotateAngleUD.
Referenced by CheckCamera().
{
        m_rotateAngleUD += m_deltaAngleUD;
        m_lookY = sin(m_rotateAngleUD);
        callGLLookAt();
}
void Camera::SetPlains (const int & moveX, const int & moveZ) [private]
Definition at line 262 of file camera.cpp.
References PlainLinkedList::GetListSize(), PlainLinkedList::GetType(), PlainLinkedList::GetXend(), PlainLinkedList::GetXstart(), PlainLinkedList::GetYend(), PlainLinkedList::GetYstart(), PlainLinkedList::GetZend(), PlainLinkedList::GetZstart(), m_incrementX, m_incrementZ, m_No_Plains, m_Plain, m_plainHeight, m_plainNo, m_x, m_xLast, m_y, m_z, m_zLast, CSound::Play(), and stepSound.
{
        // store number of plains (stops from looping through linked list each time)
        if (m_No_Plains == 0) m_No_Plains = m_Plain.GetListSize();
        for (int i = 0;  i < m_No_Plains; i++)
        {
                // if camera is positioned on a plain
                if ((m_z <= m_Plain.GetZend(i)) && (m_z >= m_Plain.GetZstart(i))
                        && (m_x <= m_Plain.GetXend(i)) && (m_x >= m_Plain.GetXstart(i)))
                {
                        // if flat plain
                        if (m_Plain.GetType(i) == 0)
{
                                m_y = m_Plain.GetYstart(i);
                                if ((m_plainNo != i) && m_plainHeight != m_Plain.GetYstart(i))
{
                                        stepSound->Play();
                                }
                                m_plainNo = i;
                                m_plainHeight = m_Plain.GetYstart(i);
                        }
                        // if plain slopes in z direction
                        if (m_Plain.GetType(i) == 2)
{
                                // if plain slopes up or down
                                if (m_zLast > m_z)
{
                                        m_incrementZ = ((m_y - m_Plain.GetYstart(i)) / (m_z - m_Plain.GetZstart(i)));
                                }
                                else
{
                                        m_incrementZ = ((m_Plain.GetYend(i) - m_y) / (m_Plain.GetZend(i) - m_z));
                                }
                                m_y += (m_incrementZ * moveZ);
                        }
                        // if plain slopes in x direction
                        if (m_Plain.GetType(i) == 1)
{
                                // if plain slopes up or down
                                if (m_xLast > m_x)
{
                                        m_incrementX = ((m_y - m_Plain.GetYstart(i)) / (m_x - m_Plain.GetXstart(i)));
                                }
                                else
{
                                        m_incrementX = ((m_Plain.GetYend(i) - m_y) / (m_Plain.GetXend(i) - m_x));
                                }
                                m_y += (m_incrementX * moveX);
                        }
                }
        }
}
void Camera::ResetXYZ () [private]
Definition at line 44 of file camera.cpp.
References m_lookX, m_lookXX, m_lookY, m_lookYY, m_lookZ, m_lookZZ, m_x, m_y, and m_z.
Referenced by Camera(), and Position().
{
        m_x = 0.0f;
        m_y = 1.75f;
        m_z = 0.0f;
        m_lookX = 0.0f;
        m_lookY = 0.0f;
        m_lookZ = -1.0f;
        m_lookXX = 1.0f;
        m_lookYY = 1.0f;
        m_lookZZ = 0.0f;
}
void Camera::callGLLookAt () [private]
Definition at line 405 of file camera.cpp.
References m_lookX, m_lookY, m_lookZ, m_x, m_y, and m_z.
Referenced by LookUD(), MoveFB(), MoveLR(), MoveUD(), Position(), and RotateLR().
{
        glLoadIdentity();
        gluLookAt(m_x, m_y, m_z,
                      m_x + m_lookX, m_y + m_lookY, m_z + m_lookZ,
                          0.0f, 1.0f, 0.0f);
}
void Camera::ClimbSteps (GLdouble stepStart, GLdouble stepFinish, GLdouble stepHeight, GLdouble stepWidth, int noSteps) [private]
Definition at line 477 of file camera.cpp.
References DirectionFB(), DirectionLR(), m_direction, m_y, m_z, and m_zLast.
{
        GLdouble tempUpSteps;
        if ((m_z < stepStart) && (m_z > stepFinish))
        {
                bool stepped = false;
                if (m_z > m_zLast)
                {
                        m_direction = 1.0;
                        tempUpSteps = stepWidth;
                }
                else
                {
                        m_direction = -1.0;
                        tempUpSteps = 0.0;
                }
                for (int i = 0; i < noSteps + 1; i++)
                {
                        if ((m_z < (stepStart - (i * stepWidth) + stepWidth/2) - tempUpSteps)
                                && (m_z > (stepStart - (i * stepWidth) - stepWidth/2) - tempUpSteps))
{
                                if (stepped== false)
{
                                        m_z = stepStart - (stepWidth * i) + (m_direction * stepWidth) - tempUpSteps;
                                        m_y += stepHeight * m_direction;
                                        stepped = true;
                                        DirectionFB(0);
                                        DirectionLR(0);
                                }
                        }
                }
        }
}
void Camera::CheckSteps () [private]
Definition at line 466 of file camera.cpp.
{
        //ClimbSteps(10000.0, 9430.0, 48.0, 142.0, 4);
        //ClimbSteps(8920.0, 8210.0, 48.0, 142.0, 5);
        //ClimbSteps(7698.0, 6988.0, 48.0, 142.0, 5);
        //ClimbSteps(6476.0, 5766.0, 48.0, 142.0, 5);
}
Camera& Camera::operator= (const Camera & cam) [inline, private]
Definition at line 169 of file camera.h.
{};
Member Data Documentation
GLdouble Camera::m_incrementX [private]
Definition at line 103 of file camera.h.
Referenced by SetPlains().
GLdouble Camera::m_incrementZ [private]
Definition at line 104 of file camera.h.
Referenced by SetPlains().
int Camera::m_No_Plains [private]
Definition at line 105 of file camera.h.
Referenced by SetPlains().
int Camera::m_plainNo [private]
Definition at line 106 of file camera.h.
Referenced by SetPlains().
GLdouble Camera::m_plainHeight [private]
Definition at line 107 of file camera.h.
Referenced by SetPlains().
GLdouble Camera::m_rotateAngleLR [private]
Definition at line 110 of file camera.h.
Referenced by Camera(), Position(), and RotateLR().
GLdouble Camera::m_deltaAngleLR [private]
Definition at line 111 of file camera.h.
Referenced by Camera(), DirectionRotateLR(), RotateLR(), and RotateLROK().
GLdouble Camera::m_rotateAngleUD [private]
Definition at line 112 of file camera.h.
Referenced by Camera(), LookUD(), and Position().
GLdouble Camera::m_deltaAngleUD [private]
Definition at line 113 of file camera.h.
Referenced by Camera(), DirectionLookUD(), LookUD(), LookUDOK(), and Position().
GLdouble Camera::m_x [private]
Definition at line 116 of file camera.h.
Referenced by callGLLookAt(), GetLR(), MoveFB(), MoveLR(), MoveUD(), Position(), ResetXYZ(), and SetPlains().
GLdouble Camera::m_y [private]
Definition at line 116 of file camera.h.
Referenced by callGLLookAt(), ClimbSteps(), GetUD(), MoveFB(), MoveLR(), MoveUD(), Position(), ResetXYZ(), and SetPlains().
GLdouble Camera::m_z [private]
Definition at line 116 of file camera.h.
Referenced by callGLLookAt(), ClimbSteps(), GetFB(), MoveFB(), MoveLR(), MoveUD(), Position(), ResetXYZ(), and SetPlains().
GLdouble Camera::m_zLast [private]
Definition at line 116 of file camera.h.
Referenced by ClimbSteps(), MoveFB(), MoveLR(), and SetPlains().
GLdouble Camera::m_xLast [private]
Definition at line 116 of file camera.h.
Referenced by MoveFB(), MoveLR(), and SetPlains().
GLdouble Camera::m_lookX [private]
Definition at line 117 of file camera.h.
Referenced by callGLLookAt(), MoveFB(), Position(), ResetXYZ(), and RotateLR().
GLdouble Camera::m_lookY [private]
Definition at line 117 of file camera.h.
Referenced by callGLLookAt(), LookUD(), MoveFB(), and ResetXYZ().
GLdouble Camera::m_lookZ [private]
Definition at line 117 of file camera.h.
Referenced by callGLLookAt(), MoveFB(), Position(), ResetXYZ(), and RotateLR().
GLdouble Camera::m_lookXX [private]
Definition at line 118 of file camera.h.
Referenced by MoveLR(), MoveUD(), Position(), ResetXYZ(), and RotateLR().
GLdouble Camera::m_lookYY [private]
Definition at line 118 of file camera.h.
Referenced by MoveLR(), MoveUD(), and ResetXYZ().
GLdouble Camera::m_lookZZ [private]
Definition at line 118 of file camera.h.
Referenced by MoveLR(), MoveUD(), Position(), ResetXYZ(), and RotateLR().
GLdouble Camera::m_deltaMoveLR [private]
Definition at line 119 of file camera.h.
Referenced by Camera(), DirectionLR(), and MoveLR().
GLdouble Camera::m_deltaMoveFB [private]
Definition at line 120 of file camera.h.
Referenced by Camera(), DirectionFB(), and MoveFB().
GLdouble Camera::m_deltaMoveUD [private]
Definition at line 121 of file camera.h.
Referenced by Camera(), DirectionUD(), and MoveUD().
GLdouble Camera::m_direction [private]
Definition at line 122 of file camera.h.
Referenced by ClimbSteps().
GLdouble Camera::m_rotateSpeed [private]
Definition at line 125 of file camera.h.
Referenced by Camera(), DirectionLookUD(), DirectionRotateLR(), LookUDOK(), RotateLROK(), and SetRotateSpeed().
GLdouble Camera::m_moveSpeed [private]
Definition at line 126 of file camera.h.
Referenced by Camera(), MoveFB(), MoveLR(), MoveUD(), and SetMoveSpeed().
bool Camera::m_CollisionDetectionOn [private]
Definition at line 150 of file camera.h.
Referenced by Camera(), MoveFB(), MoveLR(), MoveUD(), and SetCollisionDetectionOn().
Collision Camera::m_colDetect [private]
Definition at line 153 of file camera.h.
Referenced by GetAABBMaxX(), GetAABBMaxY(), GetAABBMaxZ(), GetAABBMinX(), GetAABBMinY(), GetAABBMinZ(), InitiateBoundingBoxes(), MoveFB(), MoveLR(), MoveUD(), SetAABBMaxX(), SetAABBMaxY(), SetAABBMaxZ(), SetAABBMinX(), SetAABBMinY(), SetAABBMinZ(), SetNoBoundingBoxes(), and SetWorldCoordinates().
CameraMap Camera::m_map [private]
Definition at line 154 of file camera.h.
Referenced by DisplayMap(), DisplayNoExit(), and DisplayWelcomeScreen().
PlainLinkedList Camera::m_Plain [private]
Definition at line 155 of file camera.h.
Referenced by SetPlains().
CEasySound* Camera::es [private]
Definition at line 162 of file camera.h.
Referenced by Camera(), and ~Camera().
CSound* Camera::stepSound [private]
Definition at line 163 of file camera.h.
Referenced by Camera(), SetPlains(), and ~Camera().
The documentation for this class was generated from the following files:
C:/Users/Kat/Documents/PROJECTS/ICT290/2015shayLearyALL/CAMPUS_TOUR/camera.h
C:/Users/Kat/Documents/PROJECTS/ICT290/2015shayLearyALL/CAMPUS_TOUR/camera.cpp