GravityBall: PlainLinkedList Class Reference
PlainLinkedList Class Reference
#include <PlainLinkedList.h>
Public Member Functions
PlainLinkedList ()
virtual ~PlainLinkedList ()
void Clear ()
bool AddToStart (const int tempType, const GLdouble tempXs, const GLdouble tempXe, const GLdouble tempYs, const GLdouble tempYe, const GLdouble tempZs, const GLdouble tempZe)
void SetData (const int &ptrCount, const int tempType, const GLdouble tempXs, const GLdouble tempXe, const GLdouble tempYs, const GLdouble tempYe, const GLdouble tempZs, const GLdouble tempZe)
GLdouble GetType (int ptrCount)
GLdouble GetXstart (int ptrCount)
GLdouble GetXend (int ptrCount)
GLdouble GetYstart (int ptrCount)
GLdouble GetYend (int ptrCount)
GLdouble GetZstart (int ptrCount)
GLdouble GetZend (int ptrCount)
int GetListSize ()
PlainNode * GetNext () const
PlainNode * GetFirst () const
Private Member Functions
void Delete (PlainNode *before)
PlainLinkedList (const PlainLinkedList &array)
PlainLinkedList & operator= (const PlainLinkedList &array)
Private Attributes
PlainNode * m_first
Detailed Description
Definition at line 22 of file PlainLinkedList.h.
Constructor & Destructor Documentation
PlainLinkedList::PlainLinkedList () [inline]
Definition at line 26 of file PlainLinkedList.h.
References m_first.
{m_first = new PlainNode;}
virtual PlainLinkedList::~PlainLinkedList () [inline, virtual]
Definition at line 28 of file PlainLinkedList.h.
References Clear().
{Clear();}
PlainLinkedList::PlainLinkedList (const PlainLinkedList & array) [inline, private]
Definition at line 77 of file PlainLinkedList.h.
{};
Member Function Documentation
void PlainLinkedList::Clear ()
Definition at line 13 of file PlainLinkedList.cpp.
References Delete(), PlainNode::GetNext(), and m_first.
Referenced by ~PlainLinkedList().
{
        PlainNode *ptr = m_first;
        while (ptr->GetNext() != NULL)
        // clear memory
        Delete(ptr);
}
bool PlainLinkedList::AddToStart (const int tempType, const GLdouble tempXs, const GLdouble tempXe, const GLdouble tempYs, const GLdouble tempYe, const GLdouble tempZs, const GLdouble tempZe)
Definition at line 37 of file PlainLinkedList.cpp.
References PlainNode::GetNext(), m_first, PlainNode::SetData(), and PlainNode::SetNext().
Referenced by Camera::SetPlains().
{
        PlainNode *newNode;
        try
        {
                newNode = new PlainNode;
        }
        catch(...)
        {
                return false;
        }
        // add the value to the node
        newNode->SetData(tempType, tempXs, tempXe, tempYs, tempYe, tempZs, tempZe);
        // set the address of the net node
        newNode->SetNext(m_first->GetNext());
        // reset the address of the first node
        m_first->SetNext(newNode);
        return true;
}
void PlainLinkedList::SetData (const int & ptrCount, const int tempType, const GLdouble tempXs, const GLdouble tempXe, const GLdouble tempYs, const GLdouble tempYe, const GLdouble tempZs, const GLdouble tempZe)
Definition at line 178 of file PlainLinkedList.cpp.
References PlainNode::GetNext(), m_first, and PlainNode::SetData().
{
        PlainNode *ptr = (m_first);
        for (int count = 0; count < ptrCount; count++)
        {
                ptr = ptr->GetNext();
        }
        ptr->GetNext()->SetData(tempType, tempXs, tempXe, tempYs, tempYe, tempZs, tempZe);
}
GLdouble PlainLinkedList::GetType (int ptrCount)
Definition at line 65 of file PlainLinkedList.cpp.
References PlainNode::GetNext(), PlainNode::GetType(), and m_first.
Referenced by Camera::SetPlains().
{
        PlainNode *ptr = (m_first);
        for (int count = 0; count < ptrCount; count++)
        {
                ptr = ptr->GetNext();
        }
        if (ptr->GetNext() != NULL)
                return ptr->GetNext()->GetType();
        else
                return NULL;
}
GLdouble PlainLinkedList::GetXstart (int ptrCount)
Definition at line 81 of file PlainLinkedList.cpp.
References PlainNode::GetNext(), PlainNode::GetXstart(), and m_first.
Referenced by Camera::SetPlains().
{
        PlainNode *ptr = (m_first);
        for (int count = 0; count < ptrCount; count++)
        {
                ptr = ptr->GetNext();
        }
        if (ptr->GetNext() != NULL)
                return ptr->GetNext()->GetXstart();
        else
                return NULL;
}
GLdouble PlainLinkedList::GetXend (int ptrCount)
Definition at line 97 of file PlainLinkedList.cpp.
References PlainNode::GetNext(), PlainNode::GetXend(), and m_first.
Referenced by Camera::SetPlains().
{
        PlainNode *ptr = (m_first);
        for (int count = 0; count < ptrCount; count++)
        {
                ptr = ptr->GetNext();
        }
        if (ptr->GetNext() != NULL)
                return ptr->GetNext()->GetXend();
        else
                return NULL;
}
GLdouble PlainLinkedList::GetYstart (int ptrCount)
Definition at line 113 of file PlainLinkedList.cpp.
References PlainNode::GetNext(), PlainNode::GetYstart(), and m_first.
Referenced by Camera::SetPlains().
{
        PlainNode *ptr = (m_first);
        for (int count = 0; count < ptrCount; count++)
        {
                ptr = ptr->GetNext();
        }
        if (ptr->GetNext() != NULL)
                return ptr->GetNext()->GetYstart();
        else
                return NULL;
}
GLdouble PlainLinkedList::GetYend (int ptrCount)
Definition at line 129 of file PlainLinkedList.cpp.
References PlainNode::GetNext(), PlainNode::GetYend(), and m_first.
Referenced by Camera::SetPlains().
{
        PlainNode *ptr = (m_first);
        for (int count = 0; count < ptrCount; count++)
        {
                ptr = ptr->GetNext();
        }
        if (ptr->GetNext() != NULL)
                return ptr->GetNext()->GetYend();
        else
                return NULL;
}
GLdouble PlainLinkedList::GetZstart (int ptrCount)
Definition at line 145 of file PlainLinkedList.cpp.
References PlainNode::GetNext(), PlainNode::GetZstart(), and m_first.
Referenced by Camera::SetPlains().
{
        PlainNode *ptr = (m_first);
        for (int count = 0; count < ptrCount; count++)
        {
                ptr = ptr->GetNext();
        }
        if (ptr->GetNext() != NULL)
                return ptr->GetNext()->GetZstart();
        else
                return NULL;
}
GLdouble PlainLinkedList::GetZend (int ptrCount)
Definition at line 161 of file PlainLinkedList.cpp.
References PlainNode::GetNext(), PlainNode::GetZend(), and m_first.
Referenced by Camera::SetPlains().
{
        PlainNode *ptr = (m_first);
        for (int count = 0; count < ptrCount; count++)
        {
                ptr = ptr->GetNext();
        }
        if (ptr->GetNext() != NULL)
                return ptr->GetNext()->GetZend();
        else
                return NULL;
}
int PlainLinkedList::GetListSize ()
Definition at line 194 of file PlainLinkedList.cpp.
References m_first.
Referenced by Camera::SetPlains().
{
        int tmpSize = 0;
        // count size of list
        for (PlainNode *ptr = (m_first); ptr->GetNext() != NULL; ptr = ptr->GetNext())
        {
                tmpSize++;
        }
        return tmpSize;
}
PlainNode* PlainLinkedList::GetNext () const [inline]
Definition at line 62 of file PlainLinkedList.h.
References PlainNode::GetNext(), and m_first.
{return m_first->GetNext();}
PlainNode* PlainLinkedList::GetFirst () const [inline]
Definition at line 64 of file PlainLinkedList.h.
References m_first.
{return m_first;}
void PlainLinkedList::Delete (PlainNode * before) [private]
Definition at line 25 of file PlainLinkedList.cpp.
References PlainNode::GetNext(), and PlainNode::SetNext().
Referenced by Clear().
{
        PlainNode *temp = before->GetNext();
        before->SetNext(temp->GetNext());
        delete temp;
}
PlainLinkedList& PlainLinkedList::operator= (const PlainLinkedList & array) [inline, private]
Definition at line 78 of file PlainLinkedList.h.
{};
Member Data Documentation
PlainNode* PlainLinkedList::m_first [private]
Definition at line 71 of file PlainLinkedList.h.
Referenced by AddToStart(), Clear(), GetFirst(), GetListSize(), GetNext(), GetType(), GetXend(), GetXstart(), GetYend(), GetYstart(), GetZend(), GetZstart(), PlainLinkedList(), and SetData().
The documentation for this class was generated from the following files:
C:/Users/Kat/Documents/PROJECTS/ICT290/2015shayLearyALL/CAMPUS_TOUR/PlainLinkedList.h
C:/Users/Kat/Documents/PROJECTS/ICT290/2015shayLearyALL/CAMPUS_TOUR/PlainLinkedList.cpp