GravityBall: uiHUD Class Reference
uiHUD Class Reference
HUD elements.
#include <uiHUD.h>
Public Member Functions
uiHUD (int w, int h)
void updateUIHIDMembers (int w, int h)
update the members of the HUD to new screen size
void displayUIHUD (const GLuint &tempImage)
display the elements of the HUD
void displayInstruct (const GLuint &tempImage)
display the instruction Screent
void mouseUIHUD (int button, int state, int x, int y)
Function operation of mouse in this setting.
void setBallCount (int ball)
Setter for setting the current ball count ingame.
int getBallCount ()
Getter to get how many balls are in play.
float getTimeCount ()
Getter to calculate the time.
int genScore ()
function to generate the score
int getDist ()
function to calculate the distance between cam and goal
int getTotalBallCount ()
getter to find how many balls can be played
void setTotalBallCount (int currentBalls)
setter to generate how many balls are left
void hitPlanet ()
function to check if the ball is hit a planet
void resetClock ()
function to reset clock
void setClock (clock_t nclock)
setter to set clock to nclock time
void setScore (int score)
setter to set the score
void setDist (int dist)
setter to set the distance
bool getZeroClock ()
getter to get the zeroCLOCK
void setZeroClock (bool check)
setter to set the clock to false
Private Attributes
char buffer [30]
int width
int height
int cball = 0
clock_t start = clock()
int curScore = 0
int distance
int current_Balls
int hit_Planets = 0
bool zeroClock = true
Detailed Description
HUD elements.
Author:
Katherine Mann, except where noted
Version:
01
Date:
13/10/2016
Version:
02 - updated to class KJM
Date:
19/10/2016
Version:
03 - MT::update with dynamic tracking of ui elements
Date:
25/10/2016
Version:
04 - KJM added instruction screen
Date:
2/11/2016
Definition at line 24 of file uiHUD.h.
Constructor & Destructor Documentation
uiHUD::uiHUD (int w, int h)
Definition at line 3 of file uiHUD.cpp.
References updateUIHIDMembers().
{
        updateUIHIDMembers(w, h);
}
Member Function Documentation
void uiHUD::updateUIHIDMembers (int w, int h)
update the members of the HUD to new screen size
Parameters:
w - width of the screen
h - height of the screen
Definition at line 73 of file uiHUD.cpp.
References height, and width.
Referenced by reshape(), and uiHUD().
{
        width = w;
        height = h;
}
void uiHUD::displayUIHUD (const GLuint & tempImage)
display the elements of the HUD
Parameters:
tempImage - pointer to UI image passed in
Definition at line 89 of file uiHUD.cpp.
References getBallCount(), getDist(), getTimeCount(), getTotalBallCount(), height, hit_Planets, and width.
Referenced by Display().
{
        int d = 200; //width and height of hud arc
        glPushMatrix();
        glMatrixMode(GL_PROJECTION);
        glPushMatrix();
        glLoadIdentity();
        gluOrtho2D(0, width, 0, height);
        glMatrixMode(GL_MODELVIEW);
        glLoadIdentity();
        //gl depth test disabled so hud draws correctly
        glDisable(GL_DEPTH_TEST|GL_LIGHTING); // disable depth test for 2d, lighting for text
        glClear(GL_DEPTH_BUFFER_BIT);
        glEnable(GL_TEXTURE_2D); //need for tempImage
        // display images: quad is counterclockwise starting top left, texture coords are top left = 0,0
        // this will be the corners with the menu, timer, ball stats, player/score stats
        // BALL STATS
        glBindTexture(GL_TEXTURE_2D, tempImage);
        glBegin(GL_QUADS);
                glTexCoord2f(0.5, 0.0);
                glVertex2f(0, d);
                glTexCoord2f(0.5, 0.5);
                glVertex2f(0, 0);
                glTexCoord2f(1.0, 0.5);
                glVertex2f(d, 0);
                glTexCoord2f(1.0, 0.0);
                glVertex2f(d, d);
        glEnd();
        //TIMER
        glBegin(GL_QUADS);
                glTexCoord2f(0.0, 0.5);
                glVertex2f(width-d, height);
                glTexCoord2f(0.0, 1.0);
                glVertex2f(width-d, height-d);
                glTexCoord2f(0.5, 1.0);
                glVertex2f(width, height-d);
                glTexCoord2f(0.5, 0.5);
                glVertex2f(width, height);
        glEnd();
        //MENU
        glBegin(GL_QUADS);
                glTexCoord2f(0.5, 0.5);
                glVertex2f(0, height);
                glTexCoord2f(0.5, 1.0);
                glVertex2f(0, height - d);
                glTexCoord2f(1.0, 1.0);
                glVertex2f(d, height-d);
                glTexCoord2f(1.0, 0.5);
                glVertex2f(d, height);
        glEnd();
        //PLAYER/SCORE STATS
        glBegin(GL_QUADS);
                glTexCoord2f(0.0, 0.0);
                glVertex2f(width - d, d);
                glTexCoord2f(0.0, 0.5);
                glVertex2f(width-d, 0);
                glTexCoord2f(0.5, 0.5);
                glVertex2f(width, 0);
                glTexCoord2f(0.5, 0.0);
                glVertex2f(width, d);
        glEnd();
        //data will need to be converted to string in order to put on screen
        glBindTexture(GL_TEXTURE_2D, 0); //sets active to none
        glColor3f(0.498f, 1.0f, 0.0f);
        //FIX STARTS
        glRasterPos2i(30, 100);// position of balls in play counter
        glutBitmapString(GLUT_BITMAP_9_BY_15, (const unsigned char*)std::to_string(getBallCount()).c_str());  //replace with ballsInPlay variable to string **MT Changed to sing getters and sets to be converted to a string
        glRasterPos2i(100, 40);// position of balls in play counter
        glutBitmapString(GLUT_BITMAP_9_BY_15, (const unsigned char*)std::to_string(getTotalBallCount()).c_str());
        glRasterPos2i(width-110, height-30);
        glutBitmapString(GLUT_BITMAP_9_BY_15, (const unsigned char*)std::to_string(getTimeCount()).c_str());  //replace with timer variable to string
        glRasterPos2i(width-140, 20);
        glutBitmapString(GLUT_BITMAP_9_BY_15, (const unsigned char*)std::to_string(getDist()).c_str());  // replace with distFromGoal variable to string & planetsHit variable to string **MT now activly shows how far away from the goal you are
        glRasterPos2i(width - 50, 80);
        glutBitmapString(GLUT_BITMAP_9_BY_15, (const unsigned char*)std::to_string(hit_Planets).c_str());//MT** Planets hits number
        //FIX ENDS
        glEnable(GL_DEPTH_TEST|GL_LIGHTING);
        // Reset Perspective Projection
        glMatrixMode(GL_PROJECTION);
        glPopMatrix();
        glMatrixMode(GL_MODELVIEW);
        glPopMatrix();
}
void uiHUD::displayInstruct (const GLuint & tempImage)
display the instruction Screent
Parameters:
tempImage - pointer to UI image passed in
Definition at line 184 of file uiHUD.cpp.
References height, and width.
Referenced by Display().
{
        //finding centre of screen
        int wc = width / 2;
        int hc = height / 2;
        int d = 512/2; // half of width and height of screen
        glPushMatrix();
        glMatrixMode(GL_PROJECTION);
        glPushMatrix();
        glLoadIdentity();
        gluOrtho2D(0, width, 0, height);
        glMatrixMode(GL_MODELVIEW);
        glLoadIdentity();
        //gl depth test disabled so hud draws correctly
        glDisable(GL_DEPTH_TEST);
        glDisable(GL_LIGHTING);
        glClear(GL_DEPTH_BUFFER_BIT);
        glEnable(GL_TEXTURE_2D); //need for tempImage
        // display menu image at screen centre
        glBindTexture(GL_TEXTURE_2D, tempImage);
        glBegin(GL_QUADS);
        glTexCoord2f(0.0, 0.0);
        glVertex2f(wc - d, hc + d);
        glTexCoord2f(0.0, 1.0);
        glVertex2f(wc - d, hc - d);
        glTexCoord2f(1.0, 1.0);
        glVertex2f(wc + d, hc - d);
        glTexCoord2f(1.0, 0.0);
        glVertex2f(wc + d, hc + d);
        glEnd();
        glEnable(GL_DEPTH_TEST);
        glEnable(GL_LIGHTING);
        // Reset Perspective Projection
        glMatrixMode(GL_PROJECTION);
        glPopMatrix();
        glMatrixMode(GL_MODELVIEW);
        glPopMatrix();
}
void uiHUD::mouseUIHUD (int button, int state, int x, int y)
Function operation of mouse in this setting.
Parameters:
button - the button that was pressed
state
x - x position
y - y position
Definition at line 228 of file uiHUD.cpp.
References es, CEasySound::GetSound(), gVar, CEasySound::Instance(), CEasySound::Load(), CSound::Play(), and globalVariable::uiMenu.
Referenced by uiMouseHandler().
{
        //KM 15/10/2016 click noise - sourced from http://soundbible.com/1705-Click2.html
        CEasySound *es;
        CSound* clickSound;
        es = CEasySound::Instance();
        clickSound = es->GetSound(es->Load("sounds/Click2-Sebastian-759472264.wav"));
        if ((button == GLUT_LEFT_BUTTON) && (state == GLUT_DOWN))
        {
                if (x <= 200 && x >= 0 && y <= 200 && y >= 0)
                {
                        clickSound->Play();
                        gVar.uiMenu = true;
                        //pause timer & animation
                }
        }
}
void uiHUD::setBallCount (int ball)
Setter for setting the current ball count ingame.
Parameters:
ball - ball count
Definition at line 8 of file uiHUD.cpp.
References cball.
Referenced by addParticle(), DrawBalls(), and TeleportToPlanets().
{
        cball = ball;
}
int uiHUD::getBallCount ()
Getter to get how many balls are in play.
Returns:
cball
Definition at line 12 of file uiHUD.cpp.
References cball.
Referenced by displayUIHUD().
{
        return cball;
}
float uiHUD::getTimeCount ()
Getter to calculate the time.
Returns:
time
Definition at line 46 of file uiHUD.cpp.
References start, and zeroClock.
Referenced by displayUIHUD(), and genScore().
{
        clock_t end = clock();
        float seconds = (float)(end - start) / CLOCKS_PER_SEC;
        if (100 - seconds <= 0)
        {
                zeroClock = false;
        }
        return 100 - seconds;
}
int uiHUD::genScore ()
function to generate the score
Returns:
score
Definition at line 67 of file uiHUD.cpp.
References cball, curScore, and getTimeCount().
Referenced by UpdateBalls().
{
        curScore = ((getTimeCount() * 10) / cball) * 1000;
        return curScore;
}
int uiHUD::getDist ()
function to calculate the distance between cam and goal
Returns:
distance
Definition at line 17 of file uiHUD.cpp.
References distance.
Referenced by displayUIHUD().
{
        return distance;
}
int uiHUD::getTotalBallCount ()
getter to find how many balls can be played
Returns:
current_balls
Definition at line 27 of file uiHUD.cpp.
References globalVariable::ballCount, current_Balls, and gVar.
Referenced by displayUIHUD().
{
        return gVar.ballCount - current_Balls;
}
void uiHUD::setTotalBallCount (int currentBalls)
setter to generate how many balls are left
Definition at line 32 of file uiHUD.cpp.
References current_Balls.
Referenced by addParticle().
{
        current_Balls = currentBalls;
}
void uiHUD::hitPlanet ()
function to check if the ball is hit a planet
Definition at line 41 of file uiHUD.cpp.
References hit_Planets.
Referenced by UpdateBalls().
{
        hit_Planets++;
}
void uiHUD::resetClock ()
function to reset clock
Definition at line 84 of file uiHUD.cpp.
References start.
Referenced by TeleportToPlanets().
{
        start = clock();
}
void uiHUD::setClock (clock_t nclock)
setter to set clock to nclock time
Definition at line 79 of file uiHUD.cpp.
References start.
{
        start = nclock;
}
void uiHUD::setScore (int score)
setter to set the score
Definition at line 62 of file uiHUD.cpp.
References curScore.
{
        curScore = score;
}
void uiHUD::setDist (int dist)
setter to set the distance
Definition at line 22 of file uiHUD.cpp.
References distance.
Referenced by Display().
{
        distance = distances;
}
bool uiHUD::getZeroClock ()
getter to get the zeroCLOCK
Returns:
zeroClock
Definition at line 57 of file uiHUD.cpp.
References zeroClock.
Referenced by Display().
{
        return zeroClock;
}
void uiHUD::setZeroClock (bool check)
setter to set the clock to false
Definition at line 37 of file uiHUD.cpp.
References zeroClock.
Referenced by TeleportToPlanets().
{
        zeroClock = check;
}
Member Data Documentation
char uiHUD::buffer[30] [private]
Definition at line 122 of file uiHUD.h.
int uiHUD::width [private]
Definition at line 123 of file uiHUD.h.
Referenced by displayInstruct(), displayUIHUD(), and updateUIHIDMembers().
int uiHUD::height [private]
Definition at line 124 of file uiHUD.h.
Referenced by displayInstruct(), displayUIHUD(), and updateUIHIDMembers().
int uiHUD::cball = 0 [private]
Definition at line 125 of file uiHUD.h.
Referenced by genScore(), getBallCount(), and setBallCount().
clock_t uiHUD::start = clock() [private]
Definition at line 126 of file uiHUD.h.
Referenced by getTimeCount(), resetClock(), and setClock().
int uiHUD::curScore = 0 [private]
Definition at line 127 of file uiHUD.h.
Referenced by genScore(), and setScore().
int uiHUD::distance [private]
Definition at line 128 of file uiHUD.h.
Referenced by getDist(), and setDist().
int uiHUD::current_Balls [private]
Definition at line 129 of file uiHUD.h.
Referenced by getTotalBallCount(), and setTotalBallCount().
int uiHUD::hit_Planets = 0 [private]
Definition at line 130 of file uiHUD.h.
Referenced by displayUIHUD(), and hitPlanet().
bool uiHUD::zeroClock = true [private]
Definition at line 131 of file uiHUD.h.
Referenced by getTimeCount(), getZeroClock(), and setZeroClock().
The documentation for this class was generated from the following files:
C:/Users/Kat/Documents/PROJECTS/ICT290/2015shayLearyALL/CAMPUS_TOUR/uiHUD.h
C:/Users/Kat/Documents/PROJECTS/ICT290/2015shayLearyALL/CAMPUS_TOUR/uiHUD.cpp