GravityBall: C:/Users/Kat/Documents/PROJECTS/ICT290/2015shayLearyALL/CAMPUS_TOUR/main1.cpp File Reference
C:/Users/Kat/Documents/PROJECTS/ICT290/2015shayLearyALL/CAMPUS_TOUR/main1.cpp File Reference
#include <math.h>
#include <time.h>
#include "SDL.h"
#include "OBJLoader.h"
#include "globalVariable.h"
#include "uiMouseHandler.h"
#include "CollisionDetection.h"
#include <vector>
#include <string>
#include <algorithm>
#include <fstream>
#include <cstdio>
#include <GL/glut.h>
#include "camera.h"
#include "texturedPolygons.h"
Classes
struct Ball
Defines
#define PI 3.1415962654
#define XY 0
#define XZ 1
#define YZ 2
#define YZ_FLIP 3
#define XY_FLIP 4
#define FLAT_PLAIN 0
#define XY_PLAIN 1
#define ZY_PLAIN 2
#define GRASS 1
#define GRASS_2 2
#define GRASS_HILL 3
#define PAVEMENT 4
#define PAVEMENT_TOP 5
#define PAVEMENTSIDE_LEFT 6
#define PAVEMENTSIDE_RIGHT 7
#define PAVEMENTSIDE_TOP 8
#define PAVEMENT_CORNER_1 9
#define PAVEMENT_CORNER_2 10
#define PAVEMENT_FLIP 11
#define PAVEMENT_TOP_FLIP 12
#define PAVEMENT_16 13
#define DOORPAVE_1 14
#define WALL_BRICK_YZ 15
#define WALL_BRICK_XY 16
#define WALL_BRICK_XY_87WIDTH 17
#define WALL_BRICK_GAP_YZ 18
#define WALL_BRICK_GAP2_YZ 19
#define WALL_BRICK_USD_YZ 20
#define WALL_BRICK_XY_END 21
#define WALL_BRICK_YZ_END 22
#define WALL_GAP_1 23
#define WALL_BRICK_3_4 24
#define SHADOW_BRICK 25
#define WALL_BRICK_SEC_SIGN 216
#define WINDOWPOST_CHANC_FRONT 26
#define WINDOWPOST_CHANC_RIGHT 27
#define WINDOWPOST_CHANC_LEFT 28
#define WINDOWLEDGE_CHANC_FRONT 29
#define WINDOWLEDGE_CHANC_TOP 30
#define WINDOWPOST_PHYSSCI_FRONT 31
#define WINDOWPOST_PHYSSCI_RIGHT 32
#define WINDOWPOST_PHYSSCI_LEFT 33
#define WINDOWPOST_LIB_FRONT 34
#define WINDOWPOST_LIB_LEFT 35
#define WINDOWPOST_LIB_RIGHT 36
#define DOOR_POST_SECURITY 37
#define WINDOWLEDGE_PS_FRONT 38
#define WINDOWLEDGE_PS_TOP 39
#define WINDOWLEDGE_PS_BOTT 40
#define WINDOWLEDGE_LIB_A 41
#define WINDOWLEDGE_LIB_B 42
#define WINDOWLEDGE_LIB_TOP_A 43
#define WINDOWLEDGE_LIB_TOP_B 44
#define WINDOW_LEDGE_END_1 45
#define WINDOW_LEDGE_END_2 46
#define MAIN_POST 47
#define MAIN_POST_2 48
#define DOOR_POST_CHANC 49
#define DOOR_SIDEPOST_CHANC 50
#define DOOR_POST_LIB 215
#define PURPLE_POST 51
#define PURPLE_POSTSIDE 52
#define RED_POST 53
#define RED_POSTSIDE 54
#define ROOF_TOP 55
#define ROOF_TOP_LIB 56
#define ROOF_PLANKS 57
#define ROOF_BEAM_1 58
#define ROOF_PLANKS_2 59
#define ROOF_BEAM_2 60
#define BELOW_ROOF_FILL 61
#define ROOF_BEAM_3 62
#define ROOF_BEAM_4 63
#define ROOF_BEAM_3_TOP 64
#define KBLT 65
#define KBLT_EDGE 66
#define KBLT_EDGE_2 67
#define KBLT_EDGE_CORNER 68
#define KBLT_SIDE_1 69
#define KBLT_SIDE_2 70
#define NEXUS_SIGN 71
#define NEXUS_SIDE 72
#define SECURITY_SIGN 73
#define SECURITY_SIGN_2 74
#define SIGN_1 75
#define SIGN_1_SIDE_1 76
#define SIGN_1_SIDE_2 77
#define SIGN_2 78
#define SIGN_2_SIDE 79
#define PSC_SIGN 80
#define PSC_SIGN_2 81
#define CO_SIGN 82
#define STA_TRAVEL 83
#define STA_TRAVEL_EDGE 84
#define STA_TRAVEL_BRACKET 85
#define STA_TRAVEL_2 86
#define STA_TRAVEL_BOTTOM 87
#define TOILET_MEN 88
#define TOILET_WOMEN 89
#define GS_SIGN 90
#define GS_SIGN_2 91
#define GS_SIGN_EDGE 92
#define MAP_2 93
#define GLASS_BOARD 94
#define GLASS_BOARD_2 95
#define GLASS_BOARD_3 96
#define GLASS_B_SIDE 97
#define RUSTY_MAN 98
#define NO_SMOKE_SIGN 99
#define CARPET 100
#define DRINKS_SIDE 101
#define DRINKS_TOP 102
#define DRINKS_EDGE 103
#define DRINKS_SIDE_2 104
#define COKE_MACHINE 105
#define COFFEE_MACHINE 106
#define SWEET_MACHINE 107
#define MACHINE_SIDES 108
#define MACHINE_SIDES_2 109
#define TELEPHONE_BACK 110
#define TELEPHONE_FRONT 111
#define TELEPHONE_SIDE_1 112
#define TELEPHONE_FRONT_2 113
#define TELEPHONE_MAIN_SIDE 114
#define TELEPHONE_TOP_1 115
#define TELEPHONE_SIDE_2 116
#define TELEPHONE_TOP_2 117
#define TELEPHONE_BOTTOM 118
#define TELEPHONE_FILL 119
#define TELEPHONE_FRONT_3 120
#define STEPS_LIBRARY 121
#define STEPS_LIBRARY_TOP 122
#define STEP_PAVING_1 123
#define STEP_EDGE 124
#define WINDOW_1 125
#define WINDOW_2 126
#define WINDOW_3 127
#define WINDOW_4 128
#define WINDOW_5 129
#define WINDOW_6 130
#define WINDOW_7 131
#define WINDOW_8 132
#define WINDOW_9 133
#define WINDOW_10 134
#define WINDOW_11 135
#define WINDOW_12 136
#define WINDOW_13 137
#define WINDOW_14 138
#define WINDOW_14B 139
#define WINDOW_15 140
#define WINDOW_16 141
#define WINDOW_17 142
#define WINDOW_2B 143
#define WINDOW_2C 144
#define WINDOW_2US 145
#define WINDOW_3B 146
#define WINDOW_2USB 147
#define WINDOW_LIB_1 148
#define WINDOW_LIB_1A 149
#define WINDOW_LIB_1B 150
#define WINDOW_LIB_1C 151
#define WINDOW_LIB_US_A 152
#define WINDOW_LIB_US_B 153
#define WINDOW_LIB_DOOR_1 154
#define WINDOW_LIB_DOOR_2 155
#define WINDOW_LIB_LONG 156
#define ENTRANCE 157
#define ENTRANCE_2 158
#define EXIT_EAST 159
#define EXIT_WEST 220
#define CHANC_DOOR_1 160
#define CHANC_DOOR_2 161
#define WINDOW_2D 162
#define WINDOW_2E 163
#define WINDOW_1B 164
#define STEP_WINDOW 221
#define ABOVE_WINDOW_BLOCK 165
#define ABOVE_WINDOW_BLOCK_2 166
#define ABOVE_WINDOW_BLOCK_3 167
#define ABOVE_WINDOW_EDGE_3B 168
#define ABOVE_WINDOW_BLOCK_XY_3 169
#define ABOVE_LIB 170
#define ABOVE_UNDER_POSTS 171
#define ABOVE_UNDER_POSTS_2 172
#define ABOVE_WINDOW_UNDER_LIB 173
#define ABOVE_WINDOW_BLOCK_CHANC 174
#define ABOVE_WINDOW_EDGE_3B_LIB 175
#define ABOVE_WINDOW_EDGE_4B_LIB 176
#define ABOVE_UNDER_4B 177
#define ABOVE_CHANC_TEXT 178
#define ABOVE_CHANC_TEXT_2 179
#define ABOVE_PHYS_SCI_TEXT 180
#define ABOVE_CHANC_TEXT_3 181
#define ABOVE_LIB_TEXT 182
#define ABOVE_LIB_TEXT_2 183
#define ABOVE_TICKETS_TEXT 184
#define ABOVE_CHANC_EDGE 185
#define TOILET_DOOR_TOP 186
#define LIGHT 187
#define LIGHT_SUPPORT 188
#define LIGHT_SUPPORT_2 189
#define BENCH_TOP 190
#define BENCH_SIDE 191
#define BENCH_SIDE_2 192
#define BENCH_EDGE 193
#define BENCH_EDGE_TOP 194
#define BENCH_EDGE_SIDE 195
#define BENCH_EDGE_TOP_2 196
#define BENCH_EDGE_2 197
#define BENCH_EDGE_3 198
#define TICKET_COUNTER_TOP 200
#define TICKET_COUNTER_EDGE 201
#define TICKET_COUNTER_EDGE_2 202
#define TICKET_COUNTER_EDGE_3 203
#define TICKET_LEDGE 204
#define TICKET_LEDGE_EDGE 205
#define TICKET_LEDGE_EDGE_2 206
#define WALL_BRICK_STEPS_TOP 207
#define WALL_BRICK_STEPS 208
#define WALL_BRICK_STEPS_COVER 209
#define WALL_BRICK_STEPS_EDGE 210
#define WALL_BRICK_STEPS_EDGE_2 211
#define DRAINPIPE 212
#define COUNTER_TOP 213
#define COUNTER_SIDE 214
#define MAP 217
#define WELCOME 218
#define EXIT 219
#define NO_EXIT 222
#define KM 223
#define PS_AROUND_CNR 224
#define PS_CEILING 225
#define PS_DOOR 226
#define PS_DOOR_FAR 227
#define PS_DOOR_RIGHT 228
#define PS_FLOOR 229
#define PS_LEFT_WALL 230
#define PS_OPP_DOOR 231
#define PS_RIGHT 232
#define PS_RIGHT_FAR 233
#define PS_STEP_FRONT 234
#define PS_STEP_TOP 235
#define PS_TV_WALL 236
#define PS_UNDERSTAIR 237
#define PS_WALL_OPP_STAIR 238
#define PLANETS_SUN 239
#define PLANETS_MERCURY 240
#define PLANETS_VENUS 241
#define PLANETS_EARTH 242
#define PLANETS_MARS 243
#define PLANETS_JUPITER 244
#define PLANETS_SATURN 245
#define PLANETS_URANUS 246
#define PLANETS_NEPTUNE 247
#define PLANETS_PLUTO 248
#define PLANETS_SATURNRINGS 249
#define ASTEROID 250
Typedefs
typedef GLfloat planetsVar [5]
Functions
void myinit ()
void Display ()
void reshape (int w, int h)
void keys (unsigned char key, int x, int y)
void movementKeys (int key, int x, int y)
void releaseKey (int key, int x, int y)
void releaseKeys (unsigned char key, int x, int y)
void Mouse (int button, int state, int x, int y)
void mouseMove (int x, int y)
void DrawBackdrop ()
void DisplayAboveWindowBlock ()
void DisplayBench ()
void DisplayBricks ()
void DisplayChancPosts ()
void DisplayCylinders ()
void DisplayDoorPaving ()
void DisplayDoorPosts ()
void DisplayEntranceSteps ()
void DisplayExtras ()
void DisplayGrass ()
void DisplayLargerTextures ()
void DisplayLibraryPosts ()
void DisplayMainPosts ()
void DisplayPavement ()
void DisplayPhysSciPosts ()
void DisplayPurplePosts ()
void DisplayRedPosts ()
void DisplayRoof ()
void DisplayStepBricks ()
void DisplayLights ()
void DisplayECL ()
void CreateTextureList ()
void DrawGrass ()
void DrawChancPosts ()
void DrawDoorPosts ()
void DrawPurplePosts ()
void DrawRedPosts ()
void DrawMainPosts ()
void DrawAboveWindowBlock ()
void DrawDoorPaving ()
void DrawPhysSciPosts ()
void DrawLibraryPosts ()
void DrawBricks ()
void DrawPavement ()
void DrawExtras ()
void DrawRoof ()
void DrawEntranceSteps ()
void DrawLargerTextures ()
void DrawLights ()
void DrawBench ()
void DrawCylinders ()
void DrawAngledRoofBeam (int listNo, GLdouble x, GLdouble y, GLdouble z, GLdouble beamSize)
void DrawAngledRoofBeam2 (int listNo, GLdouble x, GLdouble y, GLdouble z, GLdouble beamSize)
void DrawStepBricks ()
void DrawMapExit ()
void DrawECL ()
void BindBridgeWall (GLint LR)
void BindBuildingWall ()
void BindWallPosts (GLint LR)
void IncrementFrameCount ()
void CreateTextures ()
void CreateBoundingBoxes ()
void CreatePlains ()
void DeleteImageFromMemory (unsigned char *tempImage)
void DrawBanner ()
void CheckLocationForTeleport ()
void TeleportToPlanets ()
void TeleportToBushCourt ()
void DisplayPlanets ()
void OrbitPlanets ()
void PauseSpace ()
void addParticle (float m, float r, float vx, float vy, float vz)
void DrawBalls ()
void UpdateBalls ()
void DrawCorridor ()
void DrawCorridorSteps (int stepH, int stepD, int stepW, int stepStartX, int stepStartY, int stepStartZ, int count)
int main (int argc, char **argv)
void UpdateCamCollider ()
void DisplayTest ()
Variables
GLdouble movementSpeed = 8.0
GLdouble rotationSpeed = 0.005
GLdouble stepIncrement
GLdouble angleIncrement
int frameCount = 0
clock_t lastClock = 0
float ratio
int width
int height
GLdouble step
GLdouble step2
GLdouble stepLength
GLUquadricObj * glu_cylinder
unsigned char * image = NULL
Camera cam
TexturedPolygons tp
OBJLoader obj
uiHUD uih (1000, 1000)
uiMenu uim (1000, 1000)
uiOptions uio (1000, 1000)
uiLeaderBoard uil (1000, 1000)
GLUquadric * quad
CollisionDetection colDet
struct collider_sphere Collider_Sun
struct collider_sphere Collider_Mercury
struct collider_sphere Collider_Venus
struct collider_sphere Collider_Earth
struct collider_sphere Collider_Mars
struct collider_sphere Collider_Jupiter
struct collider_sphere Collider_Saturn
struct collider_sphere Collider_Uranus
struct collider_sphere Collider_Neptune
struct collider_sphere Collider_Pluto
struct collider_AABB Player
CEasySound * es
CSound * firstSound
GLfloat light_ambient [] = { 0.0, 0.0, 0.0, 1.0 }
GLfloat light_diffuse [] = { 1.0, 1.0, 1.0, 1.0 }
GLfloat light_specular [] = { 1.0, 1.0, 1.0, 1.0 }
GLfloat light_position [] = { 512000, 0, 0, 1.0 }
GLfloat sun_colour [] = { 0.5,0.5,0.0,1.0 }
GLfloat planet_emission [] = { 0.0, 0.0, 0.0, 1.0 }
GLfloat mat_emission [] = { 1.0, 1.0, 0.0, 1.0 }
GLfloat no_mat [] = { 0, 0, 0, 0 }
GLfloat light_pos [4] = { 0.0, 0.0, 0.0, 1.0 }
GLfloat mat_specular [] = { 1.0, 1.0, 1.0, 1.0 }
GLfloat mat_shininess [] = { 100.0 }
bool InSpace = false
GLfloat SunSize = 20
GLfloat SunX = 512000
GLfloat DistMult = 10
GLfloat SizeMult = 300
static GLdouble OrbitSpeed [] = { 4.147,1.629,1,.531,.084,.033,.011,.006,.004,365 }
static GLdouble RotationSpeed [] = { 1.1,58.65,-243,1,1.03,.41,.44,-.72,.72,-6.38 }
GLfloat rotAmt [] = { 0,0,0,0,0,0,0,0,0,0 }
planetsVar allPlanets []
GLdouble RotSpeed = 0.01
const GLdouble MaxRotSpeed = 100
const GLdouble RotSpeedAlt = 0.001
GLdouble tempSpeed = 0
bool Paused = false
GLfloat TeleportToX = 34467
GLfloat TeleportToY = 13000
GLfloat TeleportToZ = 26508
GLfloat TestX = 34467
GLfloat TestY = 11450
GLfloat TestZ = 26508
GLfloat TeleportFromX = SunX
GLfloat TeleportFromY = allPlanets[0][1]
GLfloat TeleportFromZ = allPlanets[0][2] + 10000
int moveSpeed = 3
int LevelNum = 1
const GLint MAX_BALLS = 1000
struct Ball Balls [MAX_BALLS]
int current_balls = 0
struct collider_sphere Collider_Balls [MAX_BALLS]
Define Documentation
#define ABOVE_CHANC_EDGE 185
Definition at line 258 of file main1.cpp.
#define ABOVE_CHANC_TEXT 178
Definition at line 251 of file main1.cpp.
#define ABOVE_CHANC_TEXT_2 179
Definition at line 252 of file main1.cpp.
#define ABOVE_CHANC_TEXT_3 181
Definition at line 254 of file main1.cpp.
#define ABOVE_LIB 170
Definition at line 243 of file main1.cpp.
#define ABOVE_LIB_TEXT 182
Definition at line 255 of file main1.cpp.
#define ABOVE_LIB_TEXT_2 183
Definition at line 256 of file main1.cpp.
#define ABOVE_PHYS_SCI_TEXT 180
Definition at line 253 of file main1.cpp.
#define ABOVE_TICKETS_TEXT 184
Definition at line 257 of file main1.cpp.
#define ABOVE_UNDER_4B 177
Definition at line 250 of file main1.cpp.
#define ABOVE_UNDER_POSTS 171
Definition at line 244 of file main1.cpp.
#define ABOVE_UNDER_POSTS_2 172
Definition at line 245 of file main1.cpp.
#define ABOVE_WINDOW_BLOCK 165
Definition at line 238 of file main1.cpp.
#define ABOVE_WINDOW_BLOCK_2 166
Definition at line 239 of file main1.cpp.
#define ABOVE_WINDOW_BLOCK_3 167
Definition at line 240 of file main1.cpp.
#define ABOVE_WINDOW_BLOCK_CHANC 174
Definition at line 247 of file main1.cpp.
#define ABOVE_WINDOW_BLOCK_XY_3 169
Definition at line 242 of file main1.cpp.
#define ABOVE_WINDOW_EDGE_3B 168
Definition at line 241 of file main1.cpp.
#define ABOVE_WINDOW_EDGE_3B_LIB 175
Definition at line 248 of file main1.cpp.
#define ABOVE_WINDOW_EDGE_4B_LIB 176
Definition at line 249 of file main1.cpp.
#define ABOVE_WINDOW_UNDER_LIB 173
Definition at line 246 of file main1.cpp.
#define ASTEROID 250
Definition at line 332 of file main1.cpp.
#define BELOW_ROOF_FILL 61
Definition at line 123 of file main1.cpp.
#define BENCH_EDGE 193
Definition at line 268 of file main1.cpp.
#define BENCH_EDGE_2 197
Definition at line 272 of file main1.cpp.
#define BENCH_EDGE_3 198
Definition at line 273 of file main1.cpp.
#define BENCH_EDGE_SIDE 195
Definition at line 270 of file main1.cpp.
#define BENCH_EDGE_TOP 194
Definition at line 269 of file main1.cpp.
#define BENCH_EDGE_TOP_2 196
Definition at line 271 of file main1.cpp.
#define BENCH_SIDE 191
Definition at line 266 of file main1.cpp.
#define BENCH_SIDE_2 192
Definition at line 267 of file main1.cpp.
#define BENCH_TOP 190
Definition at line 265 of file main1.cpp.
#define CARPET 100
Definition at line 164 of file main1.cpp.
#define CHANC_DOOR_1 160
Definition at line 230 of file main1.cpp.
#define CHANC_DOOR_2 161
Definition at line 231 of file main1.cpp.
#define CO_SIGN 82
Definition at line 146 of file main1.cpp.
#define COFFEE_MACHINE 106
Definition at line 171 of file main1.cpp.
#define COKE_MACHINE 105
Definition at line 170 of file main1.cpp.
#define COUNTER_SIDE 214
Definition at line 291 of file main1.cpp.
#define COUNTER_TOP 213
Definition at line 290 of file main1.cpp.
#define DOOR_POST_CHANC 49
Definition at line 108 of file main1.cpp.
#define DOOR_POST_LIB 215
Definition at line 110 of file main1.cpp.
#define DOOR_POST_SECURITY 37
Definition at line 93 of file main1.cpp.
#define DOOR_SIDEPOST_CHANC 50
Definition at line 109 of file main1.cpp.
#define DOORPAVE_1 14
Definition at line 66 of file main1.cpp.
#define DRAINPIPE 212
Definition at line 289 of file main1.cpp.
#define DRINKS_EDGE 103
Definition at line 168 of file main1.cpp.
#define DRINKS_SIDE 101
Definition at line 166 of file main1.cpp.
#define DRINKS_SIDE_2 104
Definition at line 169 of file main1.cpp.
#define DRINKS_TOP 102
Definition at line 167 of file main1.cpp.
#define ENTRANCE 157
Definition at line 226 of file main1.cpp.
#define ENTRANCE_2 158
Definition at line 227 of file main1.cpp.
#define EXIT 219
Definition at line 295 of file main1.cpp.
#define EXIT_EAST 159
Definition at line 228 of file main1.cpp.
#define EXIT_WEST 220
Definition at line 229 of file main1.cpp.
#define FLAT_PLAIN 0
Definition at line 46 of file main1.cpp.
#define GLASS_B_SIDE 97
Definition at line 161 of file main1.cpp.
#define GLASS_BOARD 94
Definition at line 158 of file main1.cpp.
#define GLASS_BOARD_2 95
Definition at line 159 of file main1.cpp.
#define GLASS_BOARD_3 96
Definition at line 160 of file main1.cpp.
#define GRASS 1
Definition at line 52 of file main1.cpp.
#define GRASS_2 2
Definition at line 53 of file main1.cpp.
#define GRASS_HILL 3
Definition at line 54 of file main1.cpp.
#define GS_SIGN 90
Definition at line 154 of file main1.cpp.
#define GS_SIGN_2 91
Definition at line 155 of file main1.cpp.
#define GS_SIGN_EDGE 92
Definition at line 156 of file main1.cpp.
#define KBLT 65
Definition at line 128 of file main1.cpp.
#define KBLT_EDGE 66
Definition at line 129 of file main1.cpp.
#define KBLT_EDGE_2 67
Definition at line 130 of file main1.cpp.
#define KBLT_EDGE_CORNER 68
Definition at line 131 of file main1.cpp.
#define KBLT_SIDE_1 69
Definition at line 132 of file main1.cpp.
#define KBLT_SIDE_2 70
Definition at line 133 of file main1.cpp.
#define KM 223
Definition at line 301 of file main1.cpp.
#define LIGHT 187
Definition at line 261 of file main1.cpp.
#define LIGHT_SUPPORT 188
Definition at line 262 of file main1.cpp.
#define LIGHT_SUPPORT_2 189
Definition at line 263 of file main1.cpp.
#define MACHINE_SIDES 108
Definition at line 173 of file main1.cpp.
#define MACHINE_SIDES_2 109
Definition at line 174 of file main1.cpp.
#define MAIN_POST 47
Definition at line 105 of file main1.cpp.
#define MAIN_POST_2 48
Definition at line 106 of file main1.cpp.
#define MAP 217
Definition at line 293 of file main1.cpp.
#define MAP_2 93
Definition at line 157 of file main1.cpp.
#define NEXUS_SIDE 72
Definition at line 136 of file main1.cpp.
#define NEXUS_SIGN 71
Definition at line 135 of file main1.cpp.
#define NO_EXIT 222
Definition at line 296 of file main1.cpp.
#define NO_SMOKE_SIGN 99
Definition at line 163 of file main1.cpp.
#define PAVEMENT 4
Definition at line 56 of file main1.cpp.
#define PAVEMENT_16 13
Definition at line 65 of file main1.cpp.
#define PAVEMENT_CORNER_1 9
Definition at line 61 of file main1.cpp.
#define PAVEMENT_CORNER_2 10
Definition at line 62 of file main1.cpp.
#define PAVEMENT_FLIP 11
Definition at line 63 of file main1.cpp.
#define PAVEMENT_TOP 5
Definition at line 57 of file main1.cpp.
#define PAVEMENT_TOP_FLIP 12
Definition at line 64 of file main1.cpp.
#define PAVEMENTSIDE_LEFT 6
Definition at line 58 of file main1.cpp.
#define PAVEMENTSIDE_RIGHT 7
Definition at line 59 of file main1.cpp.
#define PAVEMENTSIDE_TOP 8
Definition at line 60 of file main1.cpp.
#define PI 3.1415962654
Definition at line 31 of file main1.cpp.
#define PLANETS_EARTH 242
Definition at line 324 of file main1.cpp.
#define PLANETS_JUPITER 244
Definition at line 326 of file main1.cpp.
#define PLANETS_MARS 243
Definition at line 325 of file main1.cpp.
#define PLANETS_MERCURY 240
Definition at line 322 of file main1.cpp.
#define PLANETS_NEPTUNE 247
Definition at line 329 of file main1.cpp.
#define PLANETS_PLUTO 248
Definition at line 330 of file main1.cpp.
#define PLANETS_SATURN 245
Definition at line 327 of file main1.cpp.
#define PLANETS_SATURNRINGS 249
Definition at line 331 of file main1.cpp.
#define PLANETS_SUN 239
Definition at line 321 of file main1.cpp.
#define PLANETS_URANUS 246
Definition at line 328 of file main1.cpp.
#define PLANETS_VENUS 241
Definition at line 323 of file main1.cpp.
#define PS_AROUND_CNR 224
Definition at line 304 of file main1.cpp.
#define PS_CEILING 225
Definition at line 305 of file main1.cpp.
#define PS_DOOR 226
Definition at line 306 of file main1.cpp.
#define PS_DOOR_FAR 227
Definition at line 307 of file main1.cpp.
#define PS_DOOR_RIGHT 228
Definition at line 308 of file main1.cpp.
#define PS_FLOOR 229
Definition at line 309 of file main1.cpp.
#define PS_LEFT_WALL 230
Definition at line 310 of file main1.cpp.
#define PS_OPP_DOOR 231
Definition at line 311 of file main1.cpp.
#define PS_RIGHT 232
Definition at line 312 of file main1.cpp.
#define PS_RIGHT_FAR 233
Definition at line 313 of file main1.cpp.
#define PS_STEP_FRONT 234
Definition at line 314 of file main1.cpp.
#define PS_STEP_TOP 235
Definition at line 315 of file main1.cpp.
#define PS_TV_WALL 236
Definition at line 316 of file main1.cpp.
#define PS_UNDERSTAIR 237
Definition at line 317 of file main1.cpp.
#define PS_WALL_OPP_STAIR 238
Definition at line 318 of file main1.cpp.
#define PSC_SIGN 80
Definition at line 144 of file main1.cpp.
#define PSC_SIGN_2 81
Definition at line 145 of file main1.cpp.
#define PURPLE_POST 51
Definition at line 112 of file main1.cpp.
#define PURPLE_POSTSIDE 52
Definition at line 113 of file main1.cpp.
#define RED_POST 53
Definition at line 114 of file main1.cpp.
#define RED_POSTSIDE 54
Definition at line 115 of file main1.cpp.
#define ROOF_BEAM_1 58
Definition at line 120 of file main1.cpp.
#define ROOF_BEAM_2 60
Definition at line 122 of file main1.cpp.
#define ROOF_BEAM_3 62
Definition at line 124 of file main1.cpp.
#define ROOF_BEAM_3_TOP 64
Definition at line 126 of file main1.cpp.
#define ROOF_BEAM_4 63
Definition at line 125 of file main1.cpp.
#define ROOF_PLANKS 57
Definition at line 119 of file main1.cpp.
#define ROOF_PLANKS_2 59
Definition at line 121 of file main1.cpp.
#define ROOF_TOP 55
Definition at line 117 of file main1.cpp.
#define ROOF_TOP_LIB 56
Definition at line 118 of file main1.cpp.
#define RUSTY_MAN 98
Definition at line 162 of file main1.cpp.
#define SECURITY_SIGN 73
Definition at line 137 of file main1.cpp.
#define SECURITY_SIGN_2 74
Definition at line 138 of file main1.cpp.
#define SHADOW_BRICK 25
Definition at line 78 of file main1.cpp.
#define SIGN_1 75
Definition at line 139 of file main1.cpp.
#define SIGN_1_SIDE_1 76
Definition at line 140 of file main1.cpp.
#define SIGN_1_SIDE_2 77
Definition at line 141 of file main1.cpp.
#define SIGN_2 78
Definition at line 142 of file main1.cpp.
#define SIGN_2_SIDE 79
Definition at line 143 of file main1.cpp.
#define STA_TRAVEL 83
Definition at line 147 of file main1.cpp.
#define STA_TRAVEL_2 86
Definition at line 150 of file main1.cpp.
#define STA_TRAVEL_BOTTOM 87
Definition at line 151 of file main1.cpp.
#define STA_TRAVEL_BRACKET 85
Definition at line 149 of file main1.cpp.
#define STA_TRAVEL_EDGE 84
Definition at line 148 of file main1.cpp.
#define STEP_EDGE 124
Definition at line 191 of file main1.cpp.
#define STEP_PAVING_1 123
Definition at line 190 of file main1.cpp.
#define STEP_WINDOW 221
Definition at line 235 of file main1.cpp.
#define STEPS_LIBRARY 121
Definition at line 188 of file main1.cpp.
#define STEPS_LIBRARY_TOP 122
Definition at line 189 of file main1.cpp.
#define SWEET_MACHINE 107
Definition at line 172 of file main1.cpp.
#define TELEPHONE_BACK 110
Definition at line 176 of file main1.cpp.
#define TELEPHONE_BOTTOM 118
Definition at line 184 of file main1.cpp.
#define TELEPHONE_FILL 119
Definition at line 185 of file main1.cpp.
#define TELEPHONE_FRONT 111
Definition at line 177 of file main1.cpp.
#define TELEPHONE_FRONT_2 113
Definition at line 179 of file main1.cpp.
#define TELEPHONE_FRONT_3 120
Definition at line 186 of file main1.cpp.
#define TELEPHONE_MAIN_SIDE 114
Definition at line 180 of file main1.cpp.
#define TELEPHONE_SIDE_1 112
Definition at line 178 of file main1.cpp.
#define TELEPHONE_SIDE_2 116
Definition at line 182 of file main1.cpp.
#define TELEPHONE_TOP_1 115
Definition at line 181 of file main1.cpp.
#define TELEPHONE_TOP_2 117
Definition at line 183 of file main1.cpp.
#define TICKET_COUNTER_EDGE 201
Definition at line 276 of file main1.cpp.
#define TICKET_COUNTER_EDGE_2 202
Definition at line 277 of file main1.cpp.
#define TICKET_COUNTER_EDGE_3 203
Definition at line 278 of file main1.cpp.
#define TICKET_COUNTER_TOP 200
Definition at line 275 of file main1.cpp.
#define TICKET_LEDGE 204
Definition at line 279 of file main1.cpp.
#define TICKET_LEDGE_EDGE 205
Definition at line 280 of file main1.cpp.
#define TICKET_LEDGE_EDGE_2 206
Definition at line 281 of file main1.cpp.
#define TOILET_DOOR_TOP 186
Definition at line 259 of file main1.cpp.
#define TOILET_MEN 88
Definition at line 152 of file main1.cpp.
#define TOILET_WOMEN 89
Definition at line 153 of file main1.cpp.
#define WALL_BRICK_3_4 24
Definition at line 77 of file main1.cpp.
#define WALL_BRICK_GAP2_YZ 19
Definition at line 72 of file main1.cpp.
#define WALL_BRICK_GAP_YZ 18
Definition at line 71 of file main1.cpp.
#define WALL_BRICK_SEC_SIGN 216
Definition at line 79 of file main1.cpp.
#define WALL_BRICK_STEPS 208
Definition at line 284 of file main1.cpp.
#define WALL_BRICK_STEPS_COVER 209
Definition at line 285 of file main1.cpp.
#define WALL_BRICK_STEPS_EDGE 210
Definition at line 286 of file main1.cpp.
#define WALL_BRICK_STEPS_EDGE_2 211
Definition at line 287 of file main1.cpp.
#define WALL_BRICK_STEPS_TOP 207
Definition at line 283 of file main1.cpp.
#define WALL_BRICK_USD_YZ 20
Definition at line 73 of file main1.cpp.
#define WALL_BRICK_XY 16
Definition at line 69 of file main1.cpp.
#define WALL_BRICK_XY_87WIDTH 17
Definition at line 70 of file main1.cpp.
#define WALL_BRICK_XY_END 21
Definition at line 74 of file main1.cpp.
#define WALL_BRICK_YZ 15
Definition at line 68 of file main1.cpp.
#define WALL_BRICK_YZ_END 22
Definition at line 75 of file main1.cpp.
#define WALL_GAP_1 23
Definition at line 76 of file main1.cpp.
#define WELCOME 218
Definition at line 294 of file main1.cpp.
#define WINDOW_1 125
Definition at line 194 of file main1.cpp.
#define WINDOW_10 134
Definition at line 203 of file main1.cpp.
#define WINDOW_11 135
Definition at line 204 of file main1.cpp.
#define WINDOW_12 136
Definition at line 205 of file main1.cpp.
#define WINDOW_13 137
Definition at line 206 of file main1.cpp.
#define WINDOW_14 138
Definition at line 207 of file main1.cpp.
#define WINDOW_14B 139
Definition at line 208 of file main1.cpp.
#define WINDOW_15 140
Definition at line 209 of file main1.cpp.
#define WINDOW_16 141
Definition at line 210 of file main1.cpp.
#define WINDOW_17 142
Definition at line 211 of file main1.cpp.
#define WINDOW_1B 164
Definition at line 234 of file main1.cpp.
#define WINDOW_2 126
Definition at line 195 of file main1.cpp.
#define WINDOW_2B 143
Definition at line 212 of file main1.cpp.
#define WINDOW_2C 144
Definition at line 213 of file main1.cpp.
#define WINDOW_2D 162
Definition at line 232 of file main1.cpp.
#define WINDOW_2E 163
Definition at line 233 of file main1.cpp.
#define WINDOW_2US 145
Definition at line 214 of file main1.cpp.
#define WINDOW_2USB 147
Definition at line 216 of file main1.cpp.
#define WINDOW_3 127
Definition at line 196 of file main1.cpp.
#define WINDOW_3B 146
Definition at line 215 of file main1.cpp.
#define WINDOW_4 128
Definition at line 197 of file main1.cpp.
#define WINDOW_5 129
Definition at line 198 of file main1.cpp.
#define WINDOW_6 130
Definition at line 199 of file main1.cpp.
#define WINDOW_7 131
Definition at line 200 of file main1.cpp.
#define WINDOW_8 132
Definition at line 201 of file main1.cpp.
#define WINDOW_9 133
Definition at line 202 of file main1.cpp.
#define WINDOW_LEDGE_END_1 45
Definition at line 102 of file main1.cpp.
#define WINDOW_LEDGE_END_2 46
Definition at line 103 of file main1.cpp.
#define WINDOW_LIB_1 148
Definition at line 217 of file main1.cpp.
#define WINDOW_LIB_1A 149
Definition at line 218 of file main1.cpp.
#define WINDOW_LIB_1B 150
Definition at line 219 of file main1.cpp.
#define WINDOW_LIB_1C 151
Definition at line 220 of file main1.cpp.
#define WINDOW_LIB_DOOR_1 154
Definition at line 223 of file main1.cpp.
#define WINDOW_LIB_DOOR_2 155
Definition at line 224 of file main1.cpp.
#define WINDOW_LIB_LONG 156
Definition at line 225 of file main1.cpp.
#define WINDOW_LIB_US_A 152
Definition at line 221 of file main1.cpp.
#define WINDOW_LIB_US_B 153
Definition at line 222 of file main1.cpp.
#define WINDOWLEDGE_CHANC_FRONT 29
Definition at line 84 of file main1.cpp.
#define WINDOWLEDGE_CHANC_TOP 30
Definition at line 85 of file main1.cpp.
#define WINDOWLEDGE_LIB_A 41
Definition at line 98 of file main1.cpp.
#define WINDOWLEDGE_LIB_B 42
Definition at line 99 of file main1.cpp.
#define WINDOWLEDGE_LIB_TOP_A 43
Definition at line 100 of file main1.cpp.
#define WINDOWLEDGE_LIB_TOP_B 44
Definition at line 101 of file main1.cpp.
#define WINDOWLEDGE_PS_BOTT 40
Definition at line 97 of file main1.cpp.
#define WINDOWLEDGE_PS_FRONT 38
Definition at line 95 of file main1.cpp.
#define WINDOWLEDGE_PS_TOP 39
Definition at line 96 of file main1.cpp.
#define WINDOWPOST_CHANC_FRONT 26
Definition at line 81 of file main1.cpp.
#define WINDOWPOST_CHANC_LEFT 28
Definition at line 83 of file main1.cpp.
#define WINDOWPOST_CHANC_RIGHT 27
Definition at line 82 of file main1.cpp.
#define WINDOWPOST_LIB_FRONT 34
Definition at line 89 of file main1.cpp.
#define WINDOWPOST_LIB_LEFT 35
Definition at line 90 of file main1.cpp.
#define WINDOWPOST_LIB_RIGHT 36
Definition at line 91 of file main1.cpp.
#define WINDOWPOST_PHYSSCI_FRONT 31
Definition at line 86 of file main1.cpp.
#define WINDOWPOST_PHYSSCI_LEFT 33
Definition at line 88 of file main1.cpp.
#define WINDOWPOST_PHYSSCI_RIGHT 32
Definition at line 87 of file main1.cpp.
#define XY 0
Definition at line 39 of file main1.cpp.
#define XY_FLIP 4
Definition at line 43 of file main1.cpp.
#define XY_PLAIN 1
Definition at line 47 of file main1.cpp.
#define XZ 1
Definition at line 40 of file main1.cpp.
#define YZ 2
Definition at line 41 of file main1.cpp.
#define YZ_FLIP 3
Definition at line 42 of file main1.cpp.
#define ZY_PLAIN 2
Definition at line 48 of file main1.cpp.
Typedef Documentation
typedef GLfloat planetsVar[5]
Definition at line 518 of file main1.cpp.
Function Documentation
void addParticle (float m, float r, float vx, float vy, float vz)
void BindBridgeWall (GLint LR)
void BindBuildingWall ()
void BindWallPosts (GLint LR)
void CheckLocationForTeleport ()
void CreateBoundingBoxes ()
void CreatePlains ()
void CreateTextureList ()
void CreateTextures ()
void DeleteImageFromMemory (unsigned char * tempImage)
void Display ()
void DisplayAboveWindowBlock ()
void DisplayBench ()
void DisplayBricks ()
void DisplayChancPosts ()
void DisplayCylinders ()
void DisplayDoorPaving ()
void DisplayDoorPosts ()
void DisplayECL ()
void DisplayEntranceSteps ()
void DisplayExtras ()
void DisplayGrass ()
void DisplayLargerTextures ()
void DisplayLibraryPosts ()
void DisplayLights ()
void DisplayMainPosts ()
void DisplayPavement ()
void DisplayPhysSciPosts ()
void DisplayPlanets ()
void DisplayPurplePosts ()
void DisplayRedPosts ()
void DisplayRoof ()
void DisplayStepBricks ()
void DisplayTest ()
Definition at line 2666 of file main1.cpp.
References TeleportFromX, TeleportFromY, and TeleportFromZ.
{
        glPushMatrix();
                glColor3f(1, 0, 0);
                glTranslatef(TeleportFromX, TeleportFromY, TeleportFromZ);
                glutSolidCube(500);
        glPopMatrix();
}
void DrawAboveWindowBlock ()
void DrawAngledRoofBeam (int listNo, GLdouble x, GLdouble y, GLdouble z, GLdouble beamSize)
void DrawAngledRoofBeam2 (int listNo, GLdouble x, GLdouble y, GLdouble z, GLdouble beamSize)
void DrawBackdrop ()
void DrawBalls ()
void DrawBanner ()
void DrawBench ()
void DrawBricks ()
void DrawChancPosts ()
void DrawCorridor ()
void DrawCorridorSteps (int stepH, int stepD, int stepW, int stepStartX, int stepStartY, int stepStartZ, int count)
void DrawCylinders ()
void DrawDoorPaving ()
void DrawDoorPosts ()
void DrawECL ()
void DrawEntranceSteps ()
void DrawExtras ()
void DrawGrass ()
void DrawLargerTextures ()
void DrawLibraryPosts ()
void DrawLights ()
void DrawMainPosts ()
void DrawMapExit ()
void DrawPavement ()
void DrawPhysSciPosts ()
void DrawPurplePosts ()
void DrawRedPosts ()
void DrawRoof ()
void DrawStepBricks ()
void IncrementFrameCount ()
void keys (unsigned char key, int x, int y)
int main (int argc, char ** argv)
Definition at line 601 of file main1.cpp.
References Display(), keys(), Mouse(), movementKeys(), myinit(), releaseKey(), releaseKeys(), and reshape().
{
        glutInit(&argc, argv);
        glutInitDisplayMode(GLUT_DEPTH | GLUT_DOUBLE | GLUT_RGBA);
        glutInitWindowPosition(0,0);
        glutInitWindowSize(1000,1000 );
        glutCreateWindow("Murdoch University Campus Tour");
        myinit();
        glutIgnoreKeyRepeat(1);
        glutSpecialFunc(movementKeys);
        glutSpecialUpFunc(releaseKey);
        glutKeyboardUpFunc (releaseKeys);
        glutKeyboardFunc(keys);
        glutDisplayFunc(Display);
        glutIdleFunc(Display);
        glutMouseFunc(Mouse);
        // ONLY USE IF REQUIRE MOUSE MOVEMENT
        //glutPassiveMotionFunc(mouseMove);
        //ShowCursor(FALSE);
        glutReshapeFunc(reshape);
        glutMainLoop();
        return(0);
}
void Mouse (int button, int state, int x, int y)
void mouseMove (int x, int y)
void movementKeys (int key, int x, int y)
void myinit ()
void OrbitPlanets ()
void PauseSpace ()
Definition at line 6256 of file main1.cpp.
References Paused, and tempSpeed.
{
        if (Paused)
        {
                RotSpeed = tempSpeed;
                Paused = false;
        }
        else
        {
                tempSpeed = RotSpeed;
                RotSpeed = 0;
                Paused = true;
        }
}
void releaseKey (int key, int x, int y)
void releaseKeys (unsigned char key, int x, int y)
void reshape (int w, int h)
void TeleportToBushCourt ()
void TeleportToPlanets ()
void UpdateBalls ()
void UpdateCamCollider ()
Definition at line 688 of file main1.cpp.
References colDet, Camera::GetFB(), Camera::GetLR(), Camera::GetUD(), and Player.
{
    float x, y, z; //MM - vars for x, y, z coords
    x =  cam.GetLR();
    y =  cam.GetUD();
    z = cam.GetFB();
    colDet.collisionInit_B(&Player, x, y, z, 10.0, 10.0,10.0); //MM - the size (10, 10) is a guess for size
}
Variable Documentation
planetsVar allPlanets[]
Initial value:
 { { 512000 , 0, 0, 20, 10 },
                                                        { 40, 0, 0, 0.003, 0.03 },
                                                        { 80, 0, 0, 0.008, 0.08 },
                                                        { 120, 0, 0, 0.009, 0.09 },
                                                        { 160, 0, 0, 0.004, 0.04 },
                                                        { 200, 0, 0, .1, 1 },
                                                        { 240, 0, 0, .083, 0.83 },
                                                        { 280, 0, 0, .036, 0.36 },
                                                        { 320, 0, 0, .035, 0.35 },
                                                        { 360, 0, 0, .001, 0.01 }
                                                        }
Definition at line 523 of file main1.cpp.
GLdouble angleIncrement
Definition at line 338 of file main1.cpp.
struct Ball Balls[MAX_BALLS]
Definition at line 584 of file main1.cpp.
Camera cam
Definition at line 370 of file main1.cpp.
CollisionDetection colDet
Definition at line 386 of file main1.cpp.
Referenced by UpdateCamCollider().
struct collider_sphere Collider_Balls[MAX_BALLS]
Definition at line 587 of file main1.cpp.
struct collider_sphere Collider_Earth
Definition at line 393 of file main1.cpp.
struct collider_sphere Collider_Jupiter
Definition at line 395 of file main1.cpp.
struct collider_sphere Collider_Mars
Definition at line 394 of file main1.cpp.
struct collider_sphere Collider_Mercury
Definition at line 391 of file main1.cpp.
struct collider_sphere Collider_Neptune
Definition at line 398 of file main1.cpp.
struct collider_sphere Collider_Pluto
Definition at line 399 of file main1.cpp.
struct collider_sphere Collider_Saturn
Definition at line 396 of file main1.cpp.
struct collider_sphere Collider_Sun
Definition at line 390 of file main1.cpp.
struct collider_sphere Collider_Uranus
Definition at line 397 of file main1.cpp.
struct collider_sphere Collider_Venus
Definition at line 392 of file main1.cpp.
int current_balls = 0
Definition at line 585 of file main1.cpp.
GLfloat DistMult = 10
Definition at line 515 of file main1.cpp.
CEasySound* es
Definition at line 494 of file main1.cpp.
CSound* firstSound
Definition at line 495 of file main1.cpp.
int frameCount = 0
Definition at line 339 of file main1.cpp.
GLUquadricObj* glu_cylinder
Definition at line 364 of file main1.cpp.
int height
Definition at line 345 of file main1.cpp.
unsigned char* image = NULL
Definition at line 367 of file main1.cpp.
bool InSpace = false
Definition at line 511 of file main1.cpp.
clock_t lastClock = 0
Definition at line 340 of file main1.cpp.
int LevelNum = 1
Definition at line 566 of file main1.cpp.
GLfloat light_ambient[] = { 0.0, 0.0, 0.0, 1.0 }
Definition at line 499 of file main1.cpp.
GLfloat light_diffuse[] = { 1.0, 1.0, 1.0, 1.0 }
Definition at line 500 of file main1.cpp.
GLfloat light_pos[4] = { 0.0, 0.0, 0.0, 1.0 }
Definition at line 507 of file main1.cpp.
GLfloat light_position[] = { 512000, 0, 0, 1.0 }
Definition at line 502 of file main1.cpp.
GLfloat light_specular[] = { 1.0, 1.0, 1.0, 1.0 }
Definition at line 501 of file main1.cpp.
GLfloat mat_emission[] = { 1.0, 1.0, 0.0, 1.0 }
Definition at line 505 of file main1.cpp.
GLfloat mat_shininess[] = { 100.0 }
Definition at line 509 of file main1.cpp.
GLfloat mat_specular[] = { 1.0, 1.0, 1.0, 1.0 }
Definition at line 508 of file main1.cpp.
const GLint MAX_BALLS = 1000
Definition at line 583 of file main1.cpp.
const GLdouble MaxRotSpeed = 100
Definition at line 537 of file main1.cpp.
GLdouble movementSpeed = 8.0
Definition at line 35 of file main1.cpp.
int moveSpeed = 3
Definition at line 565 of file main1.cpp.
GLfloat no_mat[] = { 0, 0, 0, 0 }
Definition at line 506 of file main1.cpp.
OBJLoader obj
Definition at line 374 of file main1.cpp.
GLdouble OrbitSpeed[] = { 4.147,1.629,1,.531,.084,.033,.011,.006,.004,365 } [static]
Definition at line 519 of file main1.cpp.
bool Paused = false
Definition at line 540 of file main1.cpp.
GLfloat planet_emission[] = { 0.0, 0.0, 0.0, 1.0 }
Definition at line 504 of file main1.cpp.
struct collider_AABB Player
Definition at line 402 of file main1.cpp.
Referenced by UpdateCamCollider().
GLUquadric* quad
Definition at line 383 of file main1.cpp.
float ratio
Definition at line 343 of file main1.cpp.
GLfloat rotAmt[] = { 0,0,0,0,0,0,0,0,0,0 }
Definition at line 521 of file main1.cpp.
GLdouble RotationSpeed[] = { 1.1,58.65,-243,1,1.03,.41,.44,-.72,.72,-6.38 } [static]
Definition at line 520 of file main1.cpp.
GLdouble rotationSpeed = 0.005
Definition at line 36 of file main1.cpp.
GLdouble RotSpeed = 0.01
Definition at line 536 of file main1.cpp.
const GLdouble RotSpeedAlt = 0.001
Definition at line 538 of file main1.cpp.
GLfloat SizeMult = 300
Definition at line 516 of file main1.cpp.
GLdouble step
Definition at line 361 of file main1.cpp.
GLdouble step2
Definition at line 361 of file main1.cpp.
GLdouble stepIncrement
Definition at line 337 of file main1.cpp.
GLdouble stepLength
Definition at line 361 of file main1.cpp.
GLfloat sun_colour[] = { 0.5,0.5,0.0,1.0 }
Definition at line 503 of file main1.cpp.
GLfloat SunSize = 20
Definition at line 513 of file main1.cpp.
GLfloat SunX = 512000
Definition at line 514 of file main1.cpp.
GLfloat TeleportFromX = SunX
Definition at line 552 of file main1.cpp.
GLfloat TeleportFromY = allPlanets[0][1]
Definition at line 553 of file main1.cpp.
GLfloat TeleportFromZ = allPlanets[0][2] + 10000
Definition at line 554 of file main1.cpp.
GLfloat TeleportToX = 34467
Definition at line 543 of file main1.cpp.
GLfloat TeleportToY = 13000
Definition at line 544 of file main1.cpp.
GLfloat TeleportToZ = 26508
Definition at line 545 of file main1.cpp.
GLdouble tempSpeed = 0
Definition at line 539 of file main1.cpp.
GLfloat TestX = 34467
Definition at line 548 of file main1.cpp.
GLfloat TestY = 11450
Definition at line 549 of file main1.cpp.
GLfloat TestZ = 26508
Definition at line 550 of file main1.cpp.
TexturedPolygons tp
Definition at line 371 of file main1.cpp.
uiHUD uih(1000, 1000)
uiLeaderBoard uil(1000, 1000)
uiMenu uim(1000, 1000)
uiOptions uio(1000, 1000)
int width
Definition at line 345 of file main1.cpp.