GravityBall: C:/Users/Kat/Documents/PROJECTS/ICT290/2015shayLearyALL/CAMPUS_TOUR/uiMouseHandler.cpp File Reference
C:/Users/Kat/Documents/PROJECTS/ICT290/2015shayLearyALL/CAMPUS_TOUR/uiMouseHandler.cpp File Reference
#include "uiMouseHandler.h"
Functions
bool uiMouseHandler (int button, int state, int x, int y, uiHUD &uih, uiMenu &uim, uiOptions &uio, uiLeaderBoard &uil, uiScore &uis)
Evaluates situation, if particular UI is displayed passes click & coords to that UI and returns true.
Function Documentation
bool uiMouseHandler (int button, int state, int x, int y, uiHUD & uih, uiMenu & uim, uiOptions & uio, uiLeaderBoard & uil, uiScore & uis)
Evaluates situation, if particular UI is displayed passes click & coords to that UI and returns true.
Author:
Katherine Mann
Version:
01
Date:
18/10/2016 controls which ui has control of the mouse
Parameters:
button
state
x
y
uih - pointer to the hud object
uim - pointer to the menu object
uio - pointer to the options object
uil - pointer to the leaderboard object
uis - pointer to the score object
Definition at line 3 of file uiMouseHandler.cpp.
References gVar, uiHUD::mouseUIHUD(), uiLeaderBoard::mouseUILeaderBoard(), uiMenu::mouseUIMenu(), uiOptions::mouseUIOptions(), uiScore::mouseUIScore(), globalVariable::uiHUD, globalVariable::uiLeaderBoard, globalVariable::uiMenu, globalVariable::uiOptions, and globalVariable::uiScore.
Referenced by Mouse().
{
        if (gVar.uiScore)
        {
                //std::cout << "Score has control of mouse" << std::endl;
                uis.mouseUIScore(button, state, x, y);
                return true;
        }
        else if(gVar.uiMenu)
        {
                //std::cout << "Menu has control of mouse" << std::endl;
                uim.mouseUIMenu(button, state, x, y);
                return true;
        }
        else if (gVar.uiOptions)
        {
                //std::cout << "Options has control of mouse" << std::endl;
                uio.mouseUIOptions(button, state, x, y);
                return true;
        }
        else if (gVar.uiLeaderBoard) {
                //std::cout << "LeaderBoard has control of mouse" << std::endl;
                uil.mouseUILeaderBoard(button, state, x, y);
                return true;
        }
        else if(gVar.uiHUD)
        {
                //std::cout << "HUD has control of mouse" << std::endl;
                uih.mouseUIHUD(button, state, x, y);
                return true;
        }
        else
        return false;
}